repos:
  # Conventional commit message enforcement
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, refactor, test, chore, perf]

  # SQL formatting with SQLFluff (never blocks commits)
  - repo: local
    hooks:
      - id: sqlfluff-fix-local
        name: SQLFluff Fix (Auto-format SQL)
        entry: bash -c 'for file in "$@"; do if [[ "$file" =~ ^(models|macros|tests|analyses)/.*\.sql$ ]]; then source venv/Scripts/activate && python -m sqlfluff fix "$file" --force --disable-progress-bar || true; fi; done'
        language: system
        types: [sql]
        pass_filenames: true
        require_serial: true
        verbose: false

  # Basic code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags used by dbt
      - id: check-added-large-files
      - id: check-merge-conflict
