name: 'dbt_olids'
version: '1.0'
config-version: 2

profile: 'dbt_olids'

# Display connection info when dbt runs start
on-run-start:
  - "{{ log('🔗 DBT CONNECTION: Role=' ~ target.role ~ ', Warehouse=' ~ target.warehouse ~ ', Database=' ~ target.database ~ ', Schema=' ~ target.schema ~ ', Target=' ~ target.name, info=True) }}"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

model-paths: ["models"]
analysis-paths: ["analysis"]

# Configure dbt audit schema naming
vars:
  dbt_audit_schema: "test_audit"  # Cleaner name instead of dbt_dbt_test_audit
  
  # Flu campaign configuration - Change these values to run for different campaign years
  flu_current_campaign: "flu_2025_26"     # Current flu campaign (flu_2023_24, flu_2024_25, flu_2025_26)
  flu_previous_campaign: "flu_2024_25"    # Previous flu campaign (for year-over-year comparison)
  flu_audit_end_date: "CURRENT_DATE"      # Default audit end date

  # COVID campaign configuration - Multi-campaign support
  covid_current_autumn: "covid_2025_autumn"    # Current autumn campaign
  covid_current_spring: "covid_2025_spring"    # Current spring campaign  
  covid_previous_autumn: "covid_2024_autumn"   # Previous autumn campaign
  covid_previous_spring: "covid_2025_spring"   # Previous spring campaign (for comparison)
  covid_audit_end_date: "2025-06-30"           # End of last completed campaign (spring 2025)

# Configure test failure storage (only for failures)
# Note: This creates tables for all tests, populated only on failure
# Consider removing if too many empty tables are created
tests:
  +store_failures: false  # Disabled by default to avoid clutter
  +schema: "test_audit"

models:
  dbt_olids:
    +materialized: table
    +database: "{{ env_var('SNOWFLAKE_TARGET_DATABASE') }}"
    +persist_docs:
      columns: true
    olids:
      base:
        +materialized: view
        +schema: "olids_base"
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["base"]
      stable:
        +materialized: incremental
        +schema: "olids_stable"
        +on_schema_change: fail
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["stable", "incremental"]
      staging:
        +materialized: view
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["staging"]
      intermediate:
        +materialized: table
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["intermediate"]
      marts:
        +materialized: table
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["marts"]
    
    shared:
      staging:
        +materialized: view
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["staging"]

