name: 'snowflake_hei_migration'
version: '1.0'
config-version: 2

profile: 'snowflake_hei_migration'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]

# Configure dbt audit schema naming
vars:
  dbt_audit_schema: "dbt_test_audit"  # Cleaner name instead of dbt_dbt_test_audit

models:
  snowflake_hei_migration:
    +materialized: table
    +database: DATA_LAB_NCL_TRAINING_TEMP
    staging:
      +materialized: view
      +database: DATA_LAB_NCL_TRAINING_TEMP
      # Models reading from Data_Store_OLIDS_Dummy
      olids:
        +database: DATA_LAB_NCL_TRAINING_TEMP  # Where to create the views
        +grants:
          reference_usage: ["Data_Store_OLIDS_Dummy"]  # Database we need to read from
    intermediate:
      +materialized: table
      +database: DATA_LAB_NCL_TRAINING_TEMP
    marts:
      +materialized: table
      +database: DATA_LAB_NCL_TRAINING_TEMP