name: 'snowflake_hei_migration'
version: '1.0'
config-version: 2

profile: 'snowflake_hei_migration'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]

# Configure dbt audit schema naming
vars:
  dbt_audit_schema: "test_audit"  # Cleaner name instead of dbt_dbt_test_audit
  
  # Flu campaign configuration
  flu_current_campaign: "flu_2024_25"     # Current flu campaign
  flu_previous_campaign: "flu_2023_24"    # Previous flu campaign (for comparison)
  flu_audit_end_date: "CURRENT_DATE"      # Default audit end date (override with --vars)

# Configure test failure storage (only for failures)
# Note: This creates tables for all tests, populated only on failure
# Consider removing if too many empty tables are created
tests:
  +store_failures: false  # Disabled by default to avoid clutter
  +schema: "test_audit"

models:
  snowflake_hei_migration:
    +materialized: table
    staging:
      +materialized: view
      +database: "MODELLING"
      +schema: "DBT_STAGING"
      +post-hook: "{{ add_model_comment() }}"
    intermediate:
      +materialized: table
      +database: "MODELLING"
      +post-hook: "{{ add_model_comment() }}"
      # Business area schema mappings
      diagnoses:
        +schema: "OLIDS_DIAGNOSES"
      medications:
        +schema: "OLIDS_MEDICATIONS"
      observations:
        +schema: "OLIDS_OBSERVATIONS"
      organisation:
        +schema: "OLIDS_ORGANISATION"
      person_attributes:
        +schema: "OLIDS_PERSON_ATTRIBUTES"
      programme:
        +schema: "OLIDS_PROGRAMME"
    marts:
      +materialized: table
      +database: "REPORTING"
      +post-hook: "{{ add_model_comment() }}"
      # Business area schema mappings
      clinical_safety:
        +schema: "OLIDS_CLINICAL_SAFETY"
      data_quality:
        +schema: "OLIDS_DATA_QUALITY"
      disease_registers:
        +schema: "OLIDS_DISEASE_REGISTERS"
      geography:
        +schema: "OLIDS_GEOGRAPHY"
      measures:
        +schema: "OLIDS_MEASURES"
      organisation:
        +schema: "OLIDS_ORGANISATION"
      person_demographics:
        +schema: "OLIDS_PERSON_DEMOGRAPHICS"
      person_dimensions:
        +schema: "OLIDS_PERSON_DIMENSIONS"
      person_status:
        +schema: "OLIDS_PERSON_STATUS"
      programme:
        +schema: "OLIDS_PROGRAMME"
      # Published reporting for direct care
      published_reporting_direct_care:
        +database: "PUBLISHED_REPORTING__DIRECT_CARE"
        +schema: "OLIDS_PUBLISHED"

seeds:
  snowflake_hei_migration:
    +database: "MODELLING"
    +schema: "OLIDS_REFERENCE"
