name: 'dbt_olids'
version: '1.0'
config-version: 2

profile: 'dbt_olids'

# Display connection info when dbt runs start
on-run-start:
  - "{{ log('🔗 DBT CONNECTION: Role=' ~ target.role ~ ', Warehouse=' ~ target.warehouse ~ ', Database=' ~ target.database ~ ', Schema=' ~ target.schema ~ ', Target=' ~ target.name, info=True) }}"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

model-paths: ["models"]

vars:
  dbt_audit_schema: "test_audit"

# Configure test failure storage (only for failures)
# Note: This creates tables for all tests, populated only on failure
# Consider removing if too many empty tables are created
tests:
  +store_failures: false  # Disabled by default to avoid clutter
  +schema: "test_audit"

models:
  dbt_olids:
    +materialized: table
    +database: "{{ env_var('SNOWFLAKE_TARGET_DATABASE') }}"
    +persist_docs:
      columns: true
    olids:
      base:
        +materialized: view
        +database: "DATA_LAB_OLIDS_NCL"
        +schema: "olids_base"
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["base"]
      stable:
        +materialized: incremental
        +database: "DATA_LAB_OLIDS_NCL"
        +schema: "olids"
        +on_schema_change: fail
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["stable", "incremental"]
      intermediate:
        +materialized: table
        +post-hook: ["{{ add_model_comment() }}"]
        +tags: ["intermediate"]

