CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_VALPROATE_DB_SCOPE (
    -- Core Identifiers
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    SEX VARCHAR,
    IS_CHILD_BEARING_AGE_0_55 BOOLEAN, -- From DIM_PERSON_WOMEN_CHILD_BEARING_AGE, will be TRUE for all rows

    -- Valproate Order Details (from INTERMEDIATE_VALPROATE_ORDERS_6M_LATEST)
    MOST_RECENT_VALPROATE_ORDER_DATE DATE,
    VALPROATE_MEDICATION_ORDER_ID VARCHAR,
    VALPROATE_ORDER_MEDICATION_NAME VARCHAR,
    VALPROATE_PRODUCT_TERM VARCHAR,
    VALPROATE_RECENT_ORDER_COUNT NUMBER,
    VALPROATE_ORDER_DOSE VARCHAR, 
    VALPROATE_ORDER_QUANTITY_VALUE FLOAT,    
    VALPROATE_ORDER_QUANTITY_UNIT VARCHAR,   
    VALPROATE_ORDER_DURATION_DAYS NUMBER     
)
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT
    -- Core Identifiers
    wcba.person_id,
    pat."sk_patient_id" AS sk_patient_id,
    wcba.AGE,
    wcba.SEX,
    wcba.IS_CHILD_BEARING_AGE_0_55,

    -- Valproate Order Details
    valp.MOST_RECENT_ORDER_DATE AS MOST_RECENT_VALPROATE_ORDER_DATE,
    valp.MEDICATION_ORDER_ID AS VALPROATE_MEDICATION_ORDER_ID,
    valp.ORDER_MEDICATION_NAME AS VALPROATE_ORDER_MEDICATION_NAME,
    valp.VALPROATE_PRODUCT_TERM,
    valp.RECENT_ORDER_COUNT AS VALPROATE_RECENT_ORDER_COUNT,
    valp.ORDER_DOSE AS VALPROATE_ORDER_DOSE,
    valp.ORDER_QUANTITY_VALUE AS VALPROATE_ORDER_QUANTITY_VALUE,
    valp.ORDER_QUANTITY_UNIT AS VALPROATE_ORDER_QUANTITY_UNIT,
    valp.ORDER_DURATION_DAYS AS VALPROATE_ORDER_DURATION_DAYS

FROM
    DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_WOMEN_CHILD_BEARING_AGE wcba
INNER JOIN
    DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_VALPROATE_ORDERS_6M_LATEST valp
    ON wcba.PERSON_ID = valp.PERSON_ID
INNER JOIN
    "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT_PERSON" pp
    ON wcba.PERSON_ID = pp."person_id"
INNER JOIN
    "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT" pat
    ON pp."patient_id" = pat."id"
WHERE
    wcba.IS_CHILD_BEARING_AGE_0_55 = TRUE; 