CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_CLINICAL_SAFETY_ON_VALPROATE_AND_PREGNANT (
    -- Core Identifiers
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    SEX VARCHAR,
    IS_CHILD_BEARING_AGE_0_55 BOOLEAN, -- From DIM_PERSON_WOMEN_CHILD_BEARING_AGE, will be TRUE for all rows

    -- Pregnancy Details (from FCT_PERSON_CURRENT_PREGNANT)
    LATEST_PREG_COD_DATE DATE,
    LATEST_PREGDEL_COD_DATE DATE,
    ALL_PREG_OBSERVATION_IDS ARRAY,
    ALL_PREG_CONCEPT_CODES ARRAY,
    ALL_PREG_CONCEPT_DISPLAYS ARRAY,
    ALL_PREG_SOURCE_CLUSTER_IDS ARRAY,

    -- Valproate Order Details (from INTERMEDIATE_VALPROATE_ORDERS_6M_LATEST)
    MOST_RECENT_VALPROATE_ORDER_DATE DATE,
    VALPROATE_MEDICATION_ORDER_ID VARCHAR,
    VALPROATE_MEDICATION_STATEMENT_ID VARCHAR,
    VALPROATE_ORDER_MEDICATION_NAME VARCHAR,
    VALPROATE_ORDER_DOSE VARCHAR,
    VALPROATE_ORDER_QUANTITY_VALUE FLOAT,
    VALPROATE_ORDER_QUANTITY_UNIT VARCHAR,
    VALPROATE_ORDER_DURATION_DAYS NUMBER,
    VALPROATE_STATEMENT_MEDICATION_NAME VARCHAR,
    VALPROATE_MAPPED_CONCEPT_CODE VARCHAR,
    VALPROATE_MAPPED_CONCEPT_DISPLAY VARCHAR,
    VALPROATE_PRODUCT_TERM VARCHAR,
    VALPROATE_RECENT_ORDER_COUNT NUMBER
)
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT
    -- Core Identifiers
    wcba.PERSON_ID,
    preg.SK_PATIENT_ID, -- SK_PATIENT_ID from FCT_PERSON_CURRENT_PREGNANT
    wcba.AGE,
    wcba.SEX,
    wcba.IS_CHILD_BEARING_AGE_0_55,

    -- Pregnancy Details
    preg.LATEST_PREG_COD_DATE,
    preg.LATEST_PREGDEL_COD_DATE,
    preg.ALL_PREG_OBSERVATION_IDS,
    preg.ALL_PREG_CONCEPT_CODES,
    preg.ALL_PREG_CONCEPT_DISPLAYS,
    preg.ALL_PREG_SOURCE_CLUSTER_IDS,

    -- Valproate Order Details
    valp.MOST_RECENT_ORDER_DATE AS MOST_RECENT_VALPROATE_ORDER_DATE,
    valp.MEDICATION_ORDER_ID AS VALPROATE_MEDICATION_ORDER_ID,
    valp.MEDICATION_STATEMENT_ID AS VALPROATE_MEDICATION_STATEMENT_ID,
    valp.ORDER_MEDICATION_NAME AS VALPROATE_ORDER_MEDICATION_NAME,
    valp.ORDER_DOSE AS VALPROATE_ORDER_DOSE,
    valp.ORDER_QUANTITY_VALUE AS VALPROATE_ORDER_QUANTITY_VALUE,
    valp.ORDER_QUANTITY_UNIT AS VALPROATE_ORDER_QUANTITY_UNIT,
    valp.ORDER_DURATION_DAYS AS VALPROATE_ORDER_DURATION_DAYS,
    valp.STATEMENT_MEDICATION_NAME AS VALPROATE_STATEMENT_MEDICATION_NAME,
    valp.MAPPED_CONCEPT_CODE AS VALPROATE_MAPPED_CONCEPT_CODE,
    valp.MAPPED_CONCEPT_DISPLAY AS VALPROATE_MAPPED_CONCEPT_DISPLAY,
    valp.VALPROATE_PRODUCT_TERM,
    valp.RECENT_ORDER_COUNT AS VALPROATE_RECENT_ORDER_COUNT

FROM
    DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_WOMEN_CHILD_BEARING_AGE wcba
JOIN
    DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_CURRENT_PREGNANT preg
    ON wcba.PERSON_ID = preg.PERSON_ID
JOIN
    DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_VALPROATE_ORDERS_6M_LATEST valp
    ON preg.PERSON_ID = valp.PERSON_ID
WHERE
    wcba.IS_CHILD_BEARING_AGE_0_55 = TRUE; 