{{ config(materialized='view') }}

select
    "lds_id" as lds_id,
    "id" as id,
    "lds_business_key" as lds_business_key,
    "lds_datetime_data_acquired" as lds_datetime_data_acquired,
    "lds_initial_data_received_date" as lds_initial_data_received_date,
    "lds_dataset_id" as lds_dataset_id,
    "record_owner_organisation_code" as record_owner_organisation_code,
    "person_id" as person_id,
    "patient_id" as patient_id,
    "practitioner_id" as practitioner_id,
    "appointment_id" as appointment_id,
    "episode_of_care_id" as episode_of_care_id,
    "service_provider_organisation_id" as service_provider_organisation_id,
    "clinical_effective_date" as clinical_effective_date,
    "date_precision_concept_id" as date_precision_concept_id,
    "location" as location,
    "encounter_core_concept_id" as encounter_core_concept_id,
    "age_at_event" as age_at_event,
    "age_at_event_baby" as age_at_event_baby,
    "age_at_event_neonate" as age_at_event_neonate,
    "type" as type,
    "sub_type" as sub_type,
    "admission_method" as admission_method,
    "end_date" as end_date,
    "date_recorded" as date_recorded,
    "lds_start_date_time" as lds_start_date_time,
    "lds_end_date_time" as lds_end_date_time
from {{ source("olids_masked", "ENCOUNTER") }}