CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DIABETES_TRIPLE_TARGET(
    PERSON_ID VARCHAR, -- Unique identifier for the person
    SK_PATIENT_ID VARCHAR, -- Surrogate key for the patient
    DIABETES_TYPE VARCHAR, -- Type of diabetes
    LATEST_HBA1C_DATE DATE, -- Date of latest HbA1c
    LATEST_HBA1C_VALUE NUMBER, -- Latest HbA1c value (mmol/mol)
    LATEST_BP_DATE DATE, -- Date of latest BP
    LATEST_SYSTOLIC NUMBER, -- Latest systolic BP
    LATEST_DIASTOLIC NUMBER, -- Latest diastolic BP
    LATEST_CHOL_DATE DATE, -- Date of latest total cholesterol
    LATEST_CHOL_VALUE NUMBER, -- Latest total cholesterol (mmol/L)
    HBA1C_IN_TARGET_RANGE BOOLEAN, -- Latest HbA1c is in target range (< 58 mmol/mol)
    BP_IN_TARGET_RANGE BOOLEAN, -- Latest BP is in target range (Systolic < 140 and Diastolic < 80)
    CHOLESTEROL_IN_TARGET_RANGE BOOLEAN, -- Latest cholesterol is in target range (< 5 mmol/L)
    ALL_THREE_TARGETS_MET BOOLEAN, -- All three targets met
    HBA1C_MEASURED_IN_LAST_12M BOOLEAN, -- HbA1c measured in last 12 months
    BP_MEASURED_IN_LAST_12M BOOLEAN, -- BP measured in last 12 months
    CHOLESTEROL_MEASURED_IN_LAST_12M BOOLEAN, -- Cholesterol measured in last 12 months
    HBA1C_RECENT_BUT_OUT_OF_RANGE BOOLEAN, -- Recent HbA1c but not in target range
    BP_RECENT_BUT_OUT_OF_RANGE BOOLEAN, -- Recent BP but not in target range
    CHOLESTEROL_RECENT_BUT_OUT_OF_RANGE BOOLEAN -- Recent cholesterol but not in target range
)
TARGET_LAG = '4 hours'
WAREHOUSE = 'NCL_ANALYTICS_XS'
COMMENT = 'Fact table for the diabetes triple target. Includes latest HbA1c, blood pressure, and total cholesterol results for people on the diabetes register. Flags indicate:
- HBA1C_IN_TARGET_RANGE: HbA1c < 58 mmol/mol
- BP_IN_TARGET_RANGE: Systolic < 140 mmHg AND Diastolic < 80 mmHg
- CHOLESTEROL_IN_TARGET_RANGE: Total cholesterol < 5 mmol/L
- ALL_THREE_TARGETS_MET: All three targets met
- [MEASURE]_MEASURED_IN_LAST_12M: Latest result within the last 12 months
- [MEASURE]_RECENT_BUT_OUT_OF_RANGE: Recent result present but not in target range.'
AS
SELECT
    d.PERSON_ID,
    d.SK_PATIENT_ID,
    d.DIABETES_TYPE,
    hba1c.CLINICAL_EFFECTIVE_DATE AS LATEST_HBA1C_DATE,
    hba1c.RESULT_VALUE AS LATEST_HBA1C_VALUE,
    bp.CLINICAL_EFFECTIVE_DATE AS LATEST_BP_DATE,
    bp.SYSTOLIC_VALUE AS LATEST_SYSTOLIC,
    bp.DIASTOLIC_VALUE AS LATEST_DIASTOLIC,
    chol.CLINICAL_EFFECTIVE_DATE AS LATEST_CHOL_DATE,
    chol.RESULT_VALUE AS LATEST_CHOL_VALUE,
    (hba1c.RESULT_VALUE IS NOT NULL AND hba1c.RESULT_VALUE < 58) AS HBA1C_IN_TARGET_RANGE,
    (bp.SYSTOLIC_VALUE IS NOT NULL AND bp.SYSTOLIC_VALUE < 140 AND bp.DIASTOLIC_VALUE IS NOT NULL AND bp.DIASTOLIC_VALUE < 80) AS BP_IN_TARGET_RANGE,
    (chol.RESULT_VALUE IS NOT NULL AND chol.RESULT_VALUE < 5) AS CHOLESTEROL_IN_TARGET_RANGE,
    (HBA1C_IN_TARGET_RANGE AND BP_IN_TARGET_RANGE AND CHOLESTEROL_IN_TARGET_RANGE) AS ALL_THREE_TARGETS_MET,
    (hba1c.CLINICAL_EFFECTIVE_DATE IS NOT NULL AND DATEDIFF(month, hba1c.CLINICAL_EFFECTIVE_DATE, CURRENT_DATE()) <= 12) AS HBA1C_MEASURED_IN_LAST_12M,
    (bp.CLINICAL_EFFECTIVE_DATE IS NOT NULL AND DATEDIFF(month, bp.CLINICAL_EFFECTIVE_DATE, CURRENT_DATE()) <= 12) AS BP_MEASURED_IN_LAST_12M,
    (chol.CLINICAL_EFFECTIVE_DATE IS NOT NULL AND DATEDIFF(month, chol.CLINICAL_EFFECTIVE_DATE, CURRENT_DATE()) <= 12) AS CHOLESTEROL_MEASURED_IN_LAST_12M,
    (HBA1C_MEASURED_IN_LAST_12M AND NOT HBA1C_IN_TARGET_RANGE) AS HBA1C_RECENT_BUT_OUT_OF_RANGE,
    (BP_MEASURED_IN_LAST_12M AND NOT BP_IN_TARGET_RANGE) AS BP_RECENT_BUT_OUT_OF_RANGE,
    (CHOLESTEROL_MEASURED_IN_LAST_12M AND NOT CHOLESTEROL_IN_TARGET_RANGE) AS CHOLESTEROL_RECENT_BUT_OUT_OF_RANGE
FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_DIABETES d
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_HBA1C_LATEST hba1c
    ON d.PERSON_ID = hba1c.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_BLOOD_PRESSURE_LATEST bp
    ON d.PERSON_ID = bp.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_TOTAL_CHOLESTEROL_LATEST chol
    ON d.PERSON_ID = chol.PERSON_ID; 