CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_LTC_SUMMARY (
    PERSON_ID VARCHAR, -- Unique identifier for the person
    SK_PATIENT_ID VARCHAR, -- Surrogate key for the patient
    CONDITION_CODE VARCHAR, -- Code identifying the condition (e.g., 'AF', 'ASTHMA', 'CANCER')
    CONDITION_NAME VARCHAR, -- Display name of the condition
    IS_ON_REGISTER BOOLEAN, -- Flag indicating if person is on the condition register
    EARLIEST_DIAGNOSIS_DATE DATE, -- Earliest diagnosis date for the condition
    LATEST_DIAGNOSIS_DATE DATE -- Latest diagnosis date for the condition
)
COMMENT = 'Summary fact table of all long-term conditions, providing core register status and diagnosis dates for each condition per person. Condition codes: AF (Atrial Fibrillation), AST (Asthma), CA (Cancer), CHD (Coronary Heart Disease), CKD (Chronic Kidney Disease), COPD (Chronic Obstructive Pulmonary Disease), DEM (Dementia), DEP (Depression), DM (Diabetes), EPIL (Epilepsy), HF (Heart Failure), HTN (Hypertension), LD (Learning Disability), NDH (Non-Diabetic Hyperglycaemia), OB (Obesity), OP (Osteoporosis), PC (Palliative Care), PAD (Peripheral Arterial Disease), RA (Rheumatoid Arthritis), SMI (Serious Mental Illness), STIA (Stroke/TIA).'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS

WITH ConditionUnion AS (
    -- Atrial Fibrillation
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'AF' AS CONDITION_CODE,
        'Atrial Fibrillation' AS CONDITION_NAME,
        IS_ON_AF_REGISTER AS IS_ON_REGISTER,
        EARLIEST_AF_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_AF_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_AF

    UNION ALL

    -- Asthma
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'AST' AS CONDITION_CODE,
        'Asthma' AS CONDITION_NAME,
        IS_ON_ASTHMA_REGISTER AS IS_ON_REGISTER,
        EARLIEST_ASTHMA_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_ASTHMA_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_ASTHMA

    UNION ALL

    -- Cancer
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'CA' AS CONDITION_CODE,
        'Cancer' AS CONDITION_NAME,
        IS_ON_CANCER_REGISTER AS IS_ON_REGISTER,
        EARLIEST_CANCER_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_CANCER_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_CANCER

    UNION ALL

    -- CHD
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'CHD' AS CONDITION_CODE,
        'Coronary Heart Disease' AS CONDITION_NAME,
        IS_ON_CHD_REGISTER AS IS_ON_REGISTER,
        EARLIEST_CHD_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_CHD_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_CHD

    UNION ALL

    -- CKD
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'CKD' AS CONDITION_CODE,
        'Chronic Kidney Disease' AS CONDITION_NAME,
        IS_ON_CKD_REGISTER AS IS_ON_REGISTER,
        EARLIEST_CKD_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_CKD_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_CKD

    UNION ALL

    -- COPD
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'COPD' AS CONDITION_CODE,
        'Chronic Obstructive Pulmonary Disease' AS CONDITION_NAME,
        IS_ON_COPD_REGISTER AS IS_ON_REGISTER,
        EARLIEST_DIAGNOSIS_DATE,
        LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_COPD

    UNION ALL

    -- Dementia
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'DEM' AS CONDITION_CODE,
        'Dementia' AS CONDITION_NAME,
        IS_ON_DEM_REGISTER AS IS_ON_REGISTER,
        EARLIEST_DEM_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_DEM_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_DEMENTIA

    UNION ALL

    -- Depression
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'DEP' AS CONDITION_CODE,
        'Depression' AS CONDITION_NAME,
        IS_ON_DEPRESSION_REGISTER AS IS_ON_REGISTER,
        EARLIEST_DEPRESSION_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_DEPRESSION_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_DEPRESSION

    UNION ALL

    -- Diabetes
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'DM' AS CONDITION_CODE,
        'Diabetes' AS CONDITION_NAME,
        IS_ON_DM_REGISTER AS IS_ON_REGISTER,
        EARLIEST_DM_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_DM_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_DIABETES

    UNION ALL

    -- Epilepsy
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'EPIL' AS CONDITION_CODE,
        'Epilepsy' AS CONDITION_NAME,
        IS_ON_EPIL_REGISTER AS IS_ON_REGISTER,
        EARLIEST_EPIL_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_EPIL_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_EPILEPSY

    UNION ALL

    -- Heart Failure
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'HF' AS CONDITION_CODE,
        'Heart Failure' AS CONDITION_NAME,
        IS_ON_HF_REGISTER AS IS_ON_REGISTER,
        EARLIEST_HF_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_HF_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_HF

    UNION ALL

    -- Hypertension
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'HTN' AS CONDITION_CODE,
        'Hypertension' AS CONDITION_NAME,
        IS_ON_HTN_REGISTER AS IS_ON_REGISTER,
        EARLIEST_HTN_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_HTN_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_HYPERTENSION

    UNION ALL

    -- Learning Disability
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'LD' AS CONDITION_CODE,
        'Learning Disability' AS CONDITION_NAME,
        IS_ON_LD_REGISTER AS IS_ON_REGISTER,
        EARLIEST_LD_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_LD_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_LD

    UNION ALL

    -- Non-Diabetic Hyperglycaemia
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'NDH' AS CONDITION_CODE,
        'Non-Diabetic Hyperglycaemia' AS CONDITION_NAME,
        IS_ON_NDH_REGISTER AS IS_ON_REGISTER,
        EARLIEST_NDH_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_NDH_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_NDH

    UNION ALL

    -- Obesity
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'OB' AS CONDITION_CODE,
        'Obesity' AS CONDITION_NAME,
        IS_ON_OBESITY_REGISTER AS IS_ON_REGISTER,
        EARLIEST_BMI_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_BMI_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_OBESITY

    UNION ALL

    -- Osteoporosis
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'OP' AS CONDITION_CODE,
        'Osteoporosis' AS CONDITION_NAME,
        IS_ON_OSTEOPOROSIS_REGISTER AS IS_ON_REGISTER,
        EARLIEST_OSTEOPOROSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_OSTEOPOROSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_OSTEOPOROSIS

    UNION ALL

    -- Palliative Care
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'PC' AS CONDITION_CODE,
        'Palliative Care' AS CONDITION_NAME,
        IS_ON_PALLIATIVE_CARE_REGISTER AS IS_ON_REGISTER,
        EARLIEST_PALLIATIVE_CARE_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_PALLIATIVE_CARE_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_PALLIATIVE_CARE

    UNION ALL

    -- Peripheral Arterial Disease
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'PAD' AS CONDITION_CODE,
        'Peripheral Arterial Disease' AS CONDITION_NAME,
        IS_ON_PAD_REGISTER AS IS_ON_REGISTER,
        EARLIEST_PAD_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_PAD_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_PAD

    UNION ALL

    -- Rheumatoid Arthritis
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'RA' AS CONDITION_CODE,
        'Rheumatoid Arthritis' AS CONDITION_NAME,
        IS_ON_RA_REGISTER AS IS_ON_REGISTER,
        EARLIEST_RA_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_RA_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_RA

    UNION ALL

    -- Serious Mental Illness
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'SMI' AS CONDITION_CODE,
        'Serious Mental Illness' AS CONDITION_NAME,
        IS_ON_SMI_REGISTER AS IS_ON_REGISTER,
        EARLIEST_MH_DIAGNOSIS_DATE AS EARLIEST_DIAGNOSIS_DATE,
        LATEST_MH_DIAGNOSIS_DATE AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_SMI

    UNION ALL

    -- Stroke/TIA
    SELECT 
        PERSON_ID,
        SK_PATIENT_ID,
        'STIA' AS CONDITION_CODE,
        'Stroke or Transient Ischaemic Attack' AS CONDITION_NAME,
        IS_ON_STIA_REGISTER AS IS_ON_REGISTER,
        EARLIEST_STIA_DATE AS EARLIEST_DIAGNOSIS_DATE,
        GREATEST(COALESCE(LATEST_STROKE_DATE, LATEST_TIA_DATE), COALESCE(LATEST_TIA_DATE, LATEST_STROKE_DATE)) AS LATEST_DIAGNOSIS_DATE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_DX_STIA
)
SELECT 
    cu.PERSON_ID,
    cu.SK_PATIENT_ID,
    cu.CONDITION_CODE,
    cu.CONDITION_NAME,
    cu.IS_ON_REGISTER,
    cu.EARLIEST_DIAGNOSIS_DATE,
    cu.LATEST_DIAGNOSIS_DATE
FROM ConditionUnion cu
WHERE cu.IS_ON_REGISTER = TRUE; 