CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CODESETS.COMBINED_CODESETS (
    CLUSTER_ID,
    CLUSTER_DESCRIPTION,
    CODE,
    CODE_DESCRIPTION,
    SOURCE
)
TARGET_LAG = 'DOWNSTREAM'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
-- PCD data
SELECT
    UPPER(cluster_id) AS cluster_id,
    cluster_description,
    CAST(SNOMED_Code AS VARCHAR) AS code,
    SNOMED_Code_Description AS code_description,
    'PCD' AS source
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.pcd_refset_latest
UNION ALL
-- UKHSA COVID data
SELECT
    UPPER(CLUSTER_ID) AS cluster_id,
    CLUSTER_DESCRIPTION AS cluster_description,
    CAST(SNOMED_Code AS VARCHAR) AS code,
    SNOMED_DESCRIPTION AS code_description,
    'UKHSA_COVID' AS source
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.UKHSA_COVID_LATEST
UNION ALL
-- UKHSA FLU data
SELECT
    UPPER(CODE_GROUP) AS cluster_id,
    CODE_GROUP_DESCRIPTION AS cluster_description,
    CAST(SNOMED_Code AS VARCHAR) AS code,
    SNOMED_DESCRIPTION AS code_description,
    'UKHSA_FLU' AS source
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.UKHSA_FLU_LATEST
UNION ALL
-- LTC LCS CODES data
SELECT
    UPPER(CLUSTER_ID) AS cluster_id,
    CLUSTER_DESCRIPTION AS cluster_description,
    CAST(SNOMED_CODE AS VARCHAR) AS code,
    SNOMED_DESCRIPTION AS code_description,
    'LTC_LCS' AS source
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.LTC_LCS_CODES;
