CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CODESETS.SOURCE_CONCEPT_ORIGINS (
    SOURCE_CODE_ID_VALUE VARCHAR,
    ORIGINATING_SOURCE_TABLE VARCHAR(255)
)
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
-- PROCEDURE_REQUEST
SELECT "status_concept_id" AS SOURCE_CODE_ID_VALUE, 'PROCEDURE_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PROCEDURE_REQUEST" WHERE "status_concept_id" IS NOT NULL
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'PROCEDURE_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PROCEDURE_REQUEST" WHERE "date_precision_concept_id" IS NOT NULL
UNION
SELECT "procedure_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'PROCEDURE_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PROCEDURE_REQUEST" WHERE "procedure_core_concept_id" IS NOT NULL
-- PATIENT_ADDRESS
UNION
SELECT "address_type_concept_id" AS SOURCE_CODE_ID_VALUE, 'PATIENT_ADDRESS' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT_ADDRESS" WHERE "address_type_concept_id" IS NOT NULL
-- OBSERVATION
UNION
SELECT "result_value_unit_concept_id" AS SOURCE_CODE_ID_VALUE, 'OBSERVATION' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" WHERE "result_value_unit_concept_id" IS NOT NULL
UNION
SELECT "observation_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'OBSERVATION' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" WHERE "observation_core_concept_id" IS NOT NULL
UNION
SELECT "episodicity_concept_id" AS SOURCE_CODE_ID_VALUE, 'OBSERVATION' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" WHERE "episodicity_concept_id" IS NOT NULL
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'OBSERVATION' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" WHERE "date_precision_concept_id" IS NOT NULL
-- DIAGNOSTIC_ORDER
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'DIAGNOSTIC_ORDER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."DIAGNOSTIC_ORDER" WHERE "date_precision_concept_id" IS NOT NULL
UNION
SELECT "episodicity_concept_id" AS SOURCE_CODE_ID_VALUE, 'DIAGNOSTIC_ORDER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."DIAGNOSTIC_ORDER" WHERE "episodicity_concept_id" IS NOT NULL
UNION
SELECT "diagnostic_order_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'DIAGNOSTIC_ORDER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."DIAGNOSTIC_ORDER" WHERE "diagnostic_order_core_concept_id" IS NOT NULL
-- MEDICATION_STATEMENT
UNION
SELECT "medication_statement_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'MEDICATION_STATEMENT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."MEDICATION_STATEMENT" WHERE "medication_statement_core_concept_id" IS NOT NULL
-- ALLERGY_INTOLERANCE
UNION
SELECT "allergy_intolerance_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'ALLERGY_INTOLERANCE' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."ALLERGY_INTOLERANCE" WHERE "allergy_intolerance_core_concept_id" IS NOT NULL
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'ALLERGY_INTOLERANCE' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."ALLERGY_INTOLERANCE" WHERE "date_precision_concept_id" IS NOT NULL
-- APPOINTMENT
UNION
SELECT "contact_mode_concept_id" AS SOURCE_CODE_ID_VALUE, 'APPOINTMENT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."APPOINTMENT" WHERE "contact_mode_concept_id" IS NOT NULL
UNION
SELECT "booking_method_concept_id" AS SOURCE_CODE_ID_VALUE, 'APPOINTMENT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."APPOINTMENT" WHERE "booking_method_concept_id" IS NOT NULL
UNION
SELECT "appointment_status_concept_id" AS SOURCE_CODE_ID_VALUE, 'APPOINTMENT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."APPOINTMENT" WHERE "appointment_status_concept_id" IS NOT NULL
-- PATIENT
UNION
SELECT "gender_concept_id" AS SOURCE_CODE_ID_VALUE, 'PATIENT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT" WHERE "gender_concept_id" IS NOT NULL
-- MEDICATION_ORDER
UNION
SELECT "medication_order_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'MEDICATION_ORDER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."MEDICATION_ORDER" WHERE "medication_order_core_concept_id" IS NOT NULL
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'MEDICATION_ORDER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."MEDICATION_ORDER" WHERE "date_precision_concept_id" IS NOT NULL
-- REFERRAL_REQUEST
UNION
SELECT "referal_request_type_concept_id" AS SOURCE_CODE_ID_VALUE, 'REFERRAL_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."REFERRAL_REQUEST" WHERE "referal_request_type_concept_id" IS NOT NULL -- Typo "referal" kept
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'REFERRAL_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."REFERRAL_REQUEST" WHERE "date_precision_concept_id" IS NOT NULL
UNION
SELECT "referral_request_priority_concept_id" AS SOURCE_CODE_ID_VALUE, 'REFERRAL_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."REFERRAL_REQUEST" WHERE "referral_request_priority_concept_id" IS NOT NULL
UNION
SELECT "referral_request_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'REFERRAL_REQUEST' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."REFERRAL_REQUEST" WHERE "referral_request_core_concept_id" IS NOT NULL
-- ENCOUNTER
UNION
SELECT "date_precision_concept_id" AS SOURCE_CODE_ID_VALUE, 'ENCOUNTER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."ENCOUNTER" WHERE "date_precision_concept_id" IS NOT NULL
UNION
SELECT "encounter_core_concept_id" AS SOURCE_CODE_ID_VALUE, 'ENCOUNTER' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."ENCOUNTER" WHERE "encounter_core_concept_id" IS NOT NULL
-- LOCATION_CONTACT
UNION
SELECT "contact_type_concept_id" AS SOURCE_CODE_ID_VALUE, 'LOCATION_CONTACT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."LOCATION_CONTACT" WHERE "contact_type_concept_id" IS NOT NULL
-- PATIENT_CONTACT
UNION
SELECT "contact_type_concept_id" AS SOURCE_CODE_ID_VALUE, 'PATIENT_CONTACT' AS ORIGINATING_SOURCE_TABLE FROM "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT_CONTACT" WHERE "contact_type_concept_id" IS NOT NULL;
