/*-- CREATING CTE FOR TIME REFERENCE FOR 12 MONTH CONDITIONS/MEDICATIONS CRITERIA
WITH date_range AS (
    SELECT CAST(VARIABLEVALUE AS TIMESTAMP) AS start_date,
           CAST((SELECT VARIABLEVALUE FROM LTC_LCS_VARIABLES WHERE VARIABLENAME ='EndDate') AS TIMESTAMP) AS end_date
    FROM LTC_LCS_VARIABLES
    WHERE VARIABLENAME ='StartDate'
),*/

-- CREATING CTE USING EMIS AS SOURCE
WITH EMIS AS (

    SELECT
        EMPI_ID,
        1 AS 'EMIS'

    FROM (

        -- CREATING BASE TABLE
        WITH BASE AS (

            -- CONVERTING AGE TO MONTHS AND SELECTIING ALL AGED BETWEEN 18 MONTHS AND 17 YEARS 364 DAYS

            SELECT B.EMPI_ID
            FROM LTC_LCS_BASE AS B
            INNER JOIN NCL_MASTER_DEMOGRAPHICS AS DEM ON B.EMPI_ID = DEM.EMPI_ID
            WHERE
                DATEDIFF(DAY, DEM.BIRTH_DATE, CURRENT_DATE())
                * (12.0 / 365.25) BETWEEN 18 AND 215.9671

            -- REMOVING PATIENTS ON REGISTERS
            EXCEPT

            SELECT EMPI_ID
            FROM ICS_LTC_01

            EXCEPT

            SELECT EMPI_ID
            FROM POPHEALTH_QOF_LTCS_LIST
            WHERE LTC_NAME = 'Diabetes'

            -- REMOVING PATIENTS WITH ADDITIONAL ASTHMA CODES
            EXCEPT

            SELECT EMPI_ID
            FROM (
                SELECT
                    EMPI_ID,
                    C.CONDITION_CODE,
                    ROW_NUMBER()
                        OVER (
                            PARTITION BY EMPI_ID ORDER BY EFFECTIVE_DT_TM DESC
                        )
                        AS RN
                FROM PH_F_CONDITION AS C
                LEFT JOIN
                    JOINED_LTC_LOOKUP AS T
                    ON T.SNOMED_CODE = C.CONDITION_CODE
                WHERE T.SNOMED_CODE IN (
                    SELECT SNOMED_CODE
                    FROM JOINED_LTC_LOOKUP
                    WHERE CLUSTER_ID IN ('AST_DIAG', 'ASTRES_COD')
                )
                AND C.SOURCE_DESCRIPTION = 'EMIS GP'
            ) AS A
            WHERE
                RN = 1
                AND CONDITION_CODE != '162660004' --ASTHMA RESOLVED
        )/*,

        -- CONVERTING AGE INTO MONTHS
        AGE_MONTHS AS (
        SELECT b.EMPI_ID, DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) AS Months --, 'EMIS GP' AS SOURCE_DESCRIPTION
        FROM BASE b
        JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
        )*/

        -- CREATING A) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months till now

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B
        INNER JOIN CERNER_MEDICATION_JOINED_TABLE AS M ON B.EMPI_ID = M.EMPI_ID
        INNER JOIN JOINED_LTC_LOOKUP AS T
            ON T.SNOMED_CODE = M.DRUG_CODE
        WHERE
            T.CLUSTER_ID = 'AST_DRUG'
            --AND b.Months BETWEEN 18 AND 215.9671
            AND M.START_DT_TM BETWEEN ADD_MONTHS(
                CURRENT_DATE(), -12
            ) AND CURRENT_DATE()

            AND M.SOURCE_DESCRIPTION = 'EMIS GP'

        UNION

        -- CREATING B) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B --AGE_MONTHS b
        INNER JOIN CERNER_MEDICATION_JOINED_TABLE AS M ON B.EMPI_ID = M.EMPI_ID
        INNER JOIN JOINED_LTC_LOOKUP AS T
            ON T.SNOMED_CODE = M.DRUG_CODE
        WHERE
            T.CLUSTER_ID IN ('AST_PREDNIL', 'Montelukast')
            --AND b.Months BETWEEN 18 AND 215.9671
            AND M.START_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)

            AND M.SOURCE_DESCRIPTION = 'EMIS GP'

        UNION

        -- CREATING C) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH SUSPECTED ASTHMA or VIRAL WHEEZE CONDITIONS

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B
        INNER JOIN PH_F_CONDITION AS C ON B.EMPI_ID = C.EMPI_ID
        INNER JOIN LTC_LCS_LOOKUPTABLE AS T ON T.SNOMED_CODE = C.CONDITION_CODE
        WHERE
            T.CLUSTER_ID IN ('Sus_asthma', 'Viral_wheeze')
            --AND b.Months BETWEEN 18 AND 215.9671
            AND C.EFFECTIVE_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)

            AND C.SOURCE_DESCRIPTION = 'EMIS GP'

    /*-- CREATING C) INCLUSION COHORT FOR OVER 6 YEARS WITH A VIRAL WHEEZE
    INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID, c.SOURCE_DESCRIPTION
    FROM LTC_LCS_BASE b
    JOIN PH_F_CONDITION c USING(EMPI_ID)
    JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
    INNER JOIN date_range ON EFFECTIVE_DT_TM BETWEEN date_range.start_date AND date_range.end_date
    WHERE c.EMPI_ID = b.EMPI_ID
    AND t.cluster_id IN ()
    AND AGE >= 6
    AND c.SOURCE_DESCRIPTION = 'EMIS GP'
    )*/

    ) AS A
),

-- CREATING CTE FOR INCLUDING OTHER SOURCES AS WELL

-- CONVERTING AGE INTO MONTHS
OTHER AS (

    SELECT
        EMPI_ID,
        1 AS 'OTHER'

    FROM (

    -- CREATING BASE TABLE
        WITH BASE AS (

        -- CONVERTING AGE TO MONTHS AND SELECTIING ALL AGED BETWEEN 18 MONTHS AND 17 YEARS 364 DAYS

            SELECT B.EMPI_ID
            FROM LTC_LCS_BASE AS B
            INNER JOIN NCL_MASTER_DEMOGRAPHICS AS DEM ON B.EMPI_ID = DEM.EMPI_ID
            WHERE
                DATEDIFF(DAY, DEM.BIRTH_DATE, CURRENT_DATE())
                * (12.0 / 365.25) BETWEEN 18 AND 215.9671

            -- REMOVING PATIENTS ON REGISTERS
            EXCEPT

            SELECT EMPI_ID
            FROM ICS_LTC_01

            EXCEPT

            SELECT EMPI_ID
            FROM POPHEALTH_QOF_LTCS_LIST
            WHERE LTC_NAME = 'Diabetes'

            -- REMOVING PATIENTS WITH ADDITIONAL ASTHMA CODES
            EXCEPT

            SELECT EMPI_ID
            FROM (
                SELECT
                    EMPI_ID,
                    C.CONDITION_CODE,
                    ROW_NUMBER()
                        OVER (
                            PARTITION BY EMPI_ID ORDER BY EFFECTIVE_DT_TM DESC
                        )
                        AS RN
                FROM PH_F_CONDITION AS C
                LEFT JOIN
                    JOINED_LTC_LOOKUP AS T
                    ON T.SNOMED_CODE = C.CONDITION_CODE
                WHERE T.SNOMED_CODE IN (
                    SELECT SNOMED_CODE
                    FROM JOINED_LTC_LOOKUP
                    WHERE CLUSTER_ID IN ('AST_DIAG', 'ASTRES_COD')
                )
            ) AS A
            WHERE
                RN = 1
                AND CONDITION_CODE != '162660004' --ASTHMA RESOLVED
        )/*,

        -- CONVERTING AGE INTO MONTHS
        AGE_MONTHS AS (
        SELECT b.EMPI_ID, DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) AS Months --, 'EMIS GP' AS SOURCE_DESCRIPTION
        FROM BASE b
        JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
        )*/

        -- CREATING A) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months till now

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B
        INNER JOIN CERNER_MEDICATION_JOINED_TABLE AS M ON B.EMPI_ID = M.EMPI_ID
        INNER JOIN JOINED_LTC_LOOKUP AS T
            ON T.SNOMED_CODE = M.DRUG_CODE
        WHERE
            T.CLUSTER_ID = 'AST_DRUG'
            --AND b.Months BETWEEN 18 AND 215.9671
            AND M.START_DT_TM BETWEEN ADD_MONTHS(
                CURRENT_DATE(), -12
            ) AND CURRENT_DATE()

        UNION

        -- CREATING B) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B --AGE_MONTHS b
        INNER JOIN CERNER_MEDICATION_JOINED_TABLE AS M ON B.EMPI_ID = M.EMPI_ID
        INNER JOIN JOINED_LTC_LOOKUP AS T
            ON T.SNOMED_CODE = M.DRUG_CODE
        WHERE
            T.CLUSTER_ID IN ('AST_PREDNIL', 'Montelukast')
            --AND b.Months BETWEEN 18 AND 215.9671
            AND M.START_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)

        UNION

        -- CREATING C) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH SUSPECTED ASTHMA or VIRAL WHEEZE CONDITIONS

        SELECT DISTINCT B.EMPI_ID
        FROM BASE AS B
        INNER JOIN PH_F_CONDITION AS C ON B.EMPI_ID = C.EMPI_ID
        INNER JOIN LTC_LCS_LOOKUPTABLE AS T ON T.SNOMED_CODE = C.CONDITION_CODE
        WHERE
            T.CLUSTER_ID IN ('Sus_asthma', 'Viral_wheeze')
            --AND b.Months BETWEEN 18 AND 215.9671
            AND C.EFFECTIVE_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)

    /*-- CREATING C) INCLUSION COHORT FOR OVER 6 YEARS WITH A VIRAL WHEEZE
    INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID, c.SOURCE_DESCRIPTION
    FROM LTC_LCS_BASE b
    JOIN PH_F_CONDITION c USING(EMPI_ID)
    JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
    INNER JOIN date_range ON EFFECTIVE_DT_TM BETWEEN date_range.start_date AND date_range.end_date
    WHERE c.EMPI_ID = b.EMPI_ID
    AND t.cluster_id IN ()
    AND AGE >= 6
    AND c.SOURCE_DESCRIPTION = 'EMIS GP'
    )*/
    ) AS B
)

-- USING 'EMIS' TABLE TO GET WHOLE COHORT AND LEFT JOINING TO SEE IF OTHER AS WELL
SELECT
    COALESCE(E.EMPI_ID, O.EMPI_ID) AS EMPI_ID,
    CASE WHEN E.EMIS = 1 THEN 'EMIS' ELSE 'Other' END AS SOURCE
FROM EMIS AS E
FULL OUTER JOIN OTHER AS O ON E.EMPI_ID = O.EMPI_ID
