SELECT DISTINCT EMPI_ID
FROM LTC_LCS_BASE
WHERE AGE BETWEEN 75 and 83

EXCEPT 

SELECT EMPI_ID
FROM ICS_LTC_01

EXCEPT

SELECT EMPI_ID
FROM POPHEALTH_QOF_LTCS_LIST
WHERE LTC_NAME IN ('Diabetes', 'Palliative Care')

EXCEPT 

SELECT EMPI_ID
FROM CERNER_MEDICATION_JOINED_TABLE
WHERE DRUG_CODE IN (
                    SELECT SNOMED_CODE
                    FROM JOINED_LTC_LOOKUP
                    WHERE CLUSTER_ID = 'STAT_COD'
                    )
AND START_DT_TM >= ADD_MONTHS(CURRENT_DATE(),-12)

EXCEPT

SELECT EMPI_ID
FROM NCL_CODES
WHERE CODE IN (
                    SELECT SNOMED_CODE
                    FROM JOINED_LTC_LOOKUP
                    WHERE CLUSTER_ID IN ('STATIN_ALLERGY_ADVERSE_REACTION', 'STATIN_NOT_INDICATED')
                    )

EXCEPT

SELECT EMPI_ID
FROM NCL_CODES
WHERE CODE IN (
                    SELECT SNOMED_CODE
                    FROM JOINED_LTC_LOOKUP
                    WHERE CLUSTER_ID IN ('STATINDEC_COD')
                    )
AND DATETIME >= ADD_MONTHS(CURRENT_DATE(),-60)


EXCEPT

SELECT EMPI_ID
FROM HEALTH_CHECK_COMP_IN_24