WITH CARDIAC_RISK_SCORES_EMIS AS (
    SELECT EMPI_ID
    FROM ICB_CF_CVD_66_BASE
    WHERE NOT EXISTS (
        SELECT EMPI_ID
        FROM PH_F_RESULT
        WHERE
            RESULT_CODE IN (
                '752451000000100',
                '809311000000105',
                '718087004',
                '1085871000000105',
                '450759008',
                '763244005'
            )
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
            AND SOURCE_DESCRIPTION = 'EMIS GP'
            AND SERVICE_DATE > ADD_MONTHS(CURRENT_DATE(), -60)
            AND PH_F_RESULT.EMPI_ID = ICB_CF_CVD_66_BASE.EMPI_ID
    )
),

CARDIAC_RISK_SCORES_OTHER AS (
    SELECT EMPI_ID
    FROM ICB_CF_CVD_66_BASE
    WHERE NOT EXISTS (
        SELECT EMPI_ID
        FROM PH_F_RESULT
        WHERE
            RESULT_CODE IN (
                '752451000000100',
                '809311000000105',
                '718087004',
                '1085871000000105',
                '450759008',
                '763244005'
            )
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
            AND SERVICE_DATE > ADD_MONTHS(CURRENT_DATE(), -60)
            AND PH_F_RESULT.EMPI_ID = ICB_CF_CVD_66_BASE.EMPI_ID
    )
),

EMIS AS (SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_EMIS),

OTHER AS (SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_OTHER)

SELECT
    COALESCE(EMIS.EMPI_ID, OTHER.EMPI_ID) AS EMPI_ID,
    CASE
        WHEN EMIS.EMPI_ID IS NOT NULL THEN 'EMIS'
        ELSE 'OTHER'
    END AS SOURCE
FROM (
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_EMIS
    UNION
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_OTHER
) AS SUBQUERY
LEFT JOIN
    EMIS
    ON SUBQUERY.EMPI_ID = EMIS.EMPI_ID
LEFT JOIN
    OTHER
    ON SUBQUERY.EMPI_ID = OTHER.EMPI_ID
INNER JOIN ICB_CF_CVD_66_BASE AS BASE ON SUBQUERY.EMPI_ID = BASE.EMPI_ID
LEFT JOIN LTC_LCS_BASE AS LCS ON SUBQUERY.EMPI_ID = LCS.EMPI_ID
WHERE LCS.AGE BETWEEN 40 AND 83
