/*-- CREATING CTE FOR TIME REFERENCE FOR 12 MONTH CONDITIONS/MEDICATIONS CRITERIA
WITH date_range AS (
    SELECT CAST(VARIABLEVALUE AS TIMESTAMP) AS start_date, 
           CAST((SELECT VARIABLEVALUE FROM LTC_LCS_VARIABLES WHERE VARIABLENAME ='EndDate') AS TIMESTAMP) AS end_date
    FROM LTC_LCS_VARIABLES
    WHERE VARIABLENAME ='StartDate'
),*/

-- CREATING CTE USING EMIS AS SOURCE
with EMIS as (

select empi_id,
1 as 'EMIS'

FROM (

-- CREATING BASE TABLE
WITH BASE AS (

-- CONVERTING AGE TO MONTHS AND SELECTIING ALL AGED BETWEEN 18 MONTHS AND 17 YEARS 364 DAYS

SELECT b.EMPI_ID
from LTC_LCS_BASE B
JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
WHERE DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) BETWEEN 18 AND 215.9671

-- REMOVING PATIENTS ON REGISTERS
EXCEPT

	SELECT EMPI_ID
	FROM ICS_LTC_01

EXCEPT 

  SELECT EMPI_ID
  FROM POPHEALTH_QOF_LTCS_LIST l
  WHERE LTC_NAME = 'Diabetes'

-- REMOVING PATIENTS WITH ADDITIONAL ASTHMA CODES
EXCEPT

SELECT EMPI_ID
FROM (
  SELECT EMPI_ID, ROW_NUMBER() OVER (PARTITION BY EMPI_ID ORDER BY EFFECTIVE_DT_TM DESC) as rn, c.condition_code
  FROM PH_F_CONDITION c
  LEFT JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE	t.SNOMED_CODE	IN (SELECT SNOMED_CODE
                      FROM JOINED_LTC_LOOKUP
                      WHERE CLUSTER_ID IN ( 'AST_DIAG', 'ASTRES_COD') 
                          )
  AND c.SOURCE_DESCRIPTION = 'EMIS GP'
  						) a
  where RN = 1
  AND condition_code != '162660004' --ASTHMA RESOLVED
)/*,

-- CONVERTING AGE INTO MONTHS 
AGE_MONTHS AS (
SELECT b.EMPI_ID, DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) AS Months --, 'EMIS GP' AS SOURCE_DESCRIPTION
FROM BASE b
JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
)*/

-- CREATING A) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months till now

SELECT DISTINCT b.EMPI_ID
FROM BASE b
join CERNER_MEDICATION_JOINED_TABLE m on m.EMPI_ID = b.EMPI_ID
JOIN JOINED_LTC_LOOKUP t 
ON t.SNOMED_CODE = m.DRUG_CODE
WHERE t.cluster_id  = 'AST_DRUG'
--AND b.Months BETWEEN 18 AND 215.9671
AND m.start_dt_tm BETWEEN ADD_MONTHS(CURRENT_DATE(),-12) and CURRENT_DATE()

AND m.SOURCE_DESCRIPTION = 'EMIS GP'

UNION

-- CREATING B) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months 

SELECT DISTINCT b.EMPI_ID
FROM BASE b --AGE_MONTHS b
join CERNER_MEDICATION_JOINED_TABLE m on m.EMPI_ID = b.EMPI_ID
JOIN JOINED_LTC_LOOKUP t 
ON t.SNOMED_CODE = m.DRUG_CODE
WHERE t.cluster_id IN ('AST_PREDNIL','Montelukast')
--AND b.Months BETWEEN 18 AND 215.9671
AND m.start_dt_tm >= ADD_MONTHS(CURRENT_DATE(),-12)

AND m.SOURCE_DESCRIPTION = 'EMIS GP'

UNION

-- CREATING C) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH SUSPECTED ASTHMA or VIRAL WHEEZE CONDITIONS

SELECT DISTINCT b.EMPI_ID
FROM BASE b
JOIN PH_F_CONDITION c on b.EMPI_ID = c.EMPI_ID
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
WHERE t.CLUSTER_ID IN ('Sus_asthma', 'Viral_wheeze')
--AND b.Months BETWEEN 18 AND 215.9671
AND c.Effective_dt_tm >=ADD_MONTHS(CURRENT_DATE(),-12)

AND c.SOURCE_DESCRIPTION = 'EMIS GP'

/*-- CREATING C) INCLUSION COHORT FOR OVER 6 YEARS WITH A VIRAL WHEEZE
INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID, c.SOURCE_DESCRIPTION
FROM LTC_LCS_BASE b
JOIN PH_F_CONDITION c USING(EMPI_ID)
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
INNER JOIN date_range ON EFFECTIVE_DT_TM BETWEEN date_range.start_date AND date_range.end_date
WHERE c.EMPI_ID = b.EMPI_ID
AND t.cluster_id IN ()
AND AGE >= 6
AND c.SOURCE_DESCRIPTION = 'EMIS GP'
)*/

)a
),

-- CREATING CTE FOR INCLUDING OTHER SOURCES AS WELL

-- CONVERTING AGE INTO MONTHS
OTHER AS (

SELECT empi_id,
1 as 'OTHER'

FROM (

-- CREATING BASE TABLE
WITH BASE AS (

-- CONVERTING AGE TO MONTHS AND SELECTIING ALL AGED BETWEEN 18 MONTHS AND 17 YEARS 364 DAYS

SELECT b.EMPI_ID
from LTC_LCS_BASE B
JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
WHERE DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) BETWEEN 18 AND 215.9671

-- REMOVING PATIENTS ON REGISTERS
EXCEPT

	SELECT EMPI_ID
	FROM ICS_LTC_01

EXCEPT 

  SELECT EMPI_ID
  FROM POPHEALTH_QOF_LTCS_LIST l
  WHERE LTC_NAME = 'Diabetes'

-- REMOVING PATIENTS WITH ADDITIONAL ASTHMA CODES
EXCEPT

SELECT EMPI_ID
FROM (
  SELECT EMPI_ID, ROW_NUMBER() OVER (PARTITION BY EMPI_ID ORDER BY EFFECTIVE_DT_TM DESC) as rn, c.condition_code
  FROM PH_F_CONDITION c
  LEFT JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE	t.SNOMED_CODE	IN (SELECT SNOMED_CODE
                      FROM JOINED_LTC_LOOKUP
                      WHERE CLUSTER_ID IN ( 'AST_DIAG', 'ASTRES_COD') 
                          )
  						) a
  where RN = 1
  AND condition_code != '162660004' --ASTHMA RESOLVED
)/*,

-- CONVERTING AGE INTO MONTHS 
AGE_MONTHS AS (
SELECT b.EMPI_ID, DATEDIFF(DAY,dem.BIRTH_DATE, CURRENT_DATE())*(12.0/365.25) AS Months --, 'EMIS GP' AS SOURCE_DESCRIPTION
FROM BASE b
JOIN NCL_MASTER_DEMOGRAPHICS dem USING (EMPI_ID)
)*/

-- CREATING A) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months till now

SELECT DISTINCT b.EMPI_ID
FROM BASE b
join CERNER_MEDICATION_JOINED_TABLE m on m.EMPI_ID = b.EMPI_ID
JOIN JOINED_LTC_LOOKUP t 
ON t.SNOMED_CODE = m.DRUG_CODE
WHERE t.cluster_id  = 'AST_DRUG'
--AND b.Months BETWEEN 18 AND 215.9671
AND m.start_dt_tm BETWEEN ADD_MONTHS(CURRENT_DATE(),-12) and CURRENT_DATE()

UNION

-- CREATING B) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH DRUG CODES from -12 months 

SELECT DISTINCT b.EMPI_ID
FROM BASE b --AGE_MONTHS b
join CERNER_MEDICATION_JOINED_TABLE m on m.EMPI_ID = b.EMPI_ID
JOIN JOINED_LTC_LOOKUP t 
ON t.SNOMED_CODE = m.DRUG_CODE
WHERE t.cluster_id IN ('AST_PREDNIL','Montelukast')
--AND b.Months BETWEEN 18 AND 215.9671
AND m.start_dt_tm >= ADD_MONTHS(CURRENT_DATE(),-12)

UNION

-- CREATING C) INCLUSION COHORT FOR 18 MONTHS TO 17 YEARS WITH SUSPECTED ASTHMA or VIRAL WHEEZE CONDITIONS

SELECT DISTINCT b.EMPI_ID
FROM BASE b
JOIN PH_F_CONDITION c on b.EMPI_ID = c.EMPI_ID
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
WHERE t.CLUSTER_ID IN ('Sus_asthma', 'Viral_wheeze')
--AND b.Months BETWEEN 18 AND 215.9671
AND c.Effective_dt_tm >=ADD_MONTHS(CURRENT_DATE(),-12)

/*-- CREATING C) INCLUSION COHORT FOR OVER 6 YEARS WITH A VIRAL WHEEZE
INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID, c.SOURCE_DESCRIPTION
FROM LTC_LCS_BASE b
JOIN PH_F_CONDITION c USING(EMPI_ID)
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
INNER JOIN date_range ON EFFECTIVE_DT_TM BETWEEN date_range.start_date AND date_range.end_date
WHERE c.EMPI_ID = b.EMPI_ID
AND t.cluster_id IN ()
AND AGE >= 6
AND c.SOURCE_DESCRIPTION = 'EMIS GP'
)*/
)b
)
-- USING 'EMIS' TABLE TO GET WHOLE COHORT AND LEFT JOINING TO SEE IF OTHER AS WELL
SELECT 
COALESCE(e.empi_id, o.empi_id) as empi_id,
case when e.EMIS = 1 then 'EMIS' else 'Other' end as Source
FROM EMIS e
FULL OUTER JOIN OTHER o USING (empi_id)