-- ICB_CF_DM_63
WITH EMIS AS (

SELECT EMPI_ID, 1 AS EMIS

FROM 
(
WITH BASE_POPULATION AS 
(

SELECT DISTINCT B.EMPI_ID 

FROM LTC_LCS_BASE AS B
LEFT JOIN ICS_LTC_01 AS L1 ON L1.EMPI_ID = B.EMPI_ID
LEFT JOIN HEALTH_CHECK_COMP_IN_24 AS L2 ON L2.EMPI_ID = B.EMPI_ID

WHERE 
B.AGE >=17 AND
L1.EMPI_ID IS NULL AND 
L2.EMPI_ID IS NULL 

EXCEPT 

  SELECT EMPI_ID
  FROM POPHEALTH_QOF_LTCS_LIST l
  WHERE LTC_NAME = 'Diabetes'
)

-- Inclusions: Latest Hb1Ac value is more than or equal to 46 but less than 48 and no Hb1Ac in the last year

SELECT DISTINCT EMPI_ID

FROM
(
SELECT B.EMPI_ID, R.SERVICE_DATE, ROW_NUMBER () OVER (PARTITION BY B.EMPI_ID ORDER BY R.SERVICE_DATE DESC) AS Row_Num,
R.NORM_NUMERIC_VALUE

FROM BASE_POPULATION AS B
LEFT OUTER JOIN PH_F_RESULT AS R ON B.EMPI_ID = R.EMPI_ID
INNER JOIN JOINED_LTC_LOOKUP AS Lookup ON R.RESULT_CODE = Lookup.SNOMED_CODE

WHERE 
R.SOURCE_DESCRIPTION = 'EMIS GP' AND 
Lookup.CLUSTER_ID = 'IFCCHBAM_COD' AND 
R.NORM_NUMERIC_VALUE > 0

) AS Inclusions

WHERE Row_Num = '1' AND 
NORM_NUMERIC_VALUE >= 46 AND NORM_NUMERIC_VALUE < 48 AND  
SERVICE_DATE <= ADD_MONTHS(CURRENT_DATE(), -12)

) AS A

),

-- ICB_CF_DM_63
OTHER AS (

SELECT EMPI_ID, 1 AS OTHER

FROM 
(
WITH BASE_POPULATION AS 
(

SELECT DISTINCT B.EMPI_ID 

FROM LTC_LCS_BASE AS B
LEFT JOIN ICS_LTC_01 AS L1 ON L1.EMPI_ID = B.EMPI_ID
LEFT JOIN HEALTH_CHECK_COMP_IN_24 AS L2 ON L2.EMPI_ID = B.EMPI_ID

WHERE 
B.AGE >=17 AND
L1.EMPI_ID IS NULL AND 
L2.EMPI_ID IS NULL 
)

-- Inclusions: Latest Hb1Ac value is more than or equal to 46 but less than 48 and no Hb1Ac in the last year

SELECT DISTINCT EMPI_ID

FROM
(
SELECT B.EMPI_ID, R.SERVICE_DATE, ROW_NUMBER () OVER (PARTITION BY B.EMPI_ID ORDER BY R.SERVICE_DATE DESC) AS Row_Num,
R.NORM_NUMERIC_VALUE

FROM BASE_POPULATION AS B
LEFT OUTER JOIN PH_F_RESULT AS R ON B.EMPI_ID = R.EMPI_ID
INNER JOIN JOINED_LTC_LOOKUP AS Lookup ON R.RESULT_CODE = Lookup.SNOMED_CODE

WHERE 
--R.SOURCE_DESCRIPTION = 'EMIS GP' AND 
Lookup.CLUSTER_ID = 'IFCCHBAM_COD' AND 
R.NORM_NUMERIC_VALUE > 0

) AS Inclusions

WHERE Row_Num = '1' AND 
NORM_NUMERIC_VALUE >= 46 AND NORM_NUMERIC_VALUE < 48 AND  
SERVICE_DATE <= ADD_MONTHS(CURRENT_DATE(), -12)

) AS A

)

SELECT 
COALESCE(e.empi_id, o.empi_id) AS empi_id,
CASE WHEN e.EMIS = 1 THEN 'EMIS' ELSE 'Other' END AS Source
 
FROM EMIS AS E 
FULL OUTER JOIN OTHER AS O USING (empi_id)