WITH CARDIAC_RISK_SCORES_EMIS AS (
    SELECT
        SUB.EMPI_ID,
        SUB.NORM_NUMERIC_VALUE
    FROM (
        SELECT
            EMPI_ID,
            NORM_NUMERIC_VALUE,
            ROW_NUMBER()
                OVER (PARTITION BY EMPI_ID ORDER BY SERVICE_DATE DESC)
                AS RN
        FROM PH_F_RESULT
        WHERE
            RESULT_CODE IN (
                '752451000000100',
                '809311000000105',
                '718087004',
                '1085871000000105',
                '450759008',
                '763244005'
            )
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
            AND SOURCE_DESCRIPTION = 'EMIS GP'
            AND SERVICE_DATE < NOW()
    ) AS SUB
    INNER JOIN
        ICB_CF_CVD_61_BASE AS BASE
        ON SUB.EMPI_ID = BASE.EMPI_ID AND BASE.SOURCE = 'EMIS'
    WHERE SUB.RN = 1 AND SUB.NORM_NUMERIC_VALUE >= 20
),

CARDIAC_RISK_SCORES_OTHER AS (
    SELECT
        SUB.EMPI_ID,
        SUB.NORM_NUMERIC_VALUE
    FROM (
        SELECT
            EMPI_ID,
            NORM_NUMERIC_VALUE,
            ROW_NUMBER()
                OVER (PARTITION BY EMPI_ID ORDER BY SERVICE_DATE DESC)
                AS RN
        FROM PH_F_RESULT
        WHERE
            RESULT_CODE IN (
                '752451000000100',
                '809311000000105',
                '718087004',
                '1085871000000105',
                '450759008',
                '763244005'
            )
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
            AND SERVICE_DATE < NOW()
    ) AS SUB
    INNER JOIN ICB_CF_CVD_61_BASE AS BASE ON SUB.EMPI_ID = BASE.EMPI_ID
    WHERE SUB.RN = 1 AND SUB.NORM_NUMERIC_VALUE >= 20
)

SELECT
    COALESCE(EMIS.EMPI_ID, OTHER.EMPI_ID) AS EMPI_ID,
    CASE
        WHEN EMIS.EMPI_ID IS NOT NULL THEN 'EMIS'
        ELSE 'OTHER'
    END AS SOURCE
FROM (
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_EMIS
    UNION
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_OTHER
) AS SUBQUERY
LEFT JOIN CARDIAC_RISK_SCORES_EMIS AS EMIS ON SUBQUERY.EMPI_ID = EMIS.EMPI_ID
LEFT JOIN CARDIAC_RISK_SCORES_OTHER AS OTHER ON SUBQUERY.EMPI_ID = OTHER.EMPI_ID
