-- Staging model for olids_core.APPOINTMENT
-- Base layer: base_olids_appointment (filtered for NCL practices, excludes sensitive patients)
-- Description: Core OLIDS patient and clinical data

select
    "LakehouseDateProcessed" as lakehousedateprocessed,
    "LakehouseDateTimeUpdated" as lakehousedatetimeupdated,
    "lds_record_id" as lds_record_id,
    "lds_id" as lds_id,
    "id" as id,
    "lds_business_key" as lds_business_key,
    "lds_dataset_id" as lds_dataset_id,
    "record_owner_organisation_code" as record_owner_organisation_code,
    "lds_datetime_data_acquired" as lds_datetime_data_acquired,
    "lds_initial_data_received_date" as lds_initial_data_received_date,
    "lds_start_date_time" as lds_start_date_time,
    "organisation_id" as organisation_id,
    "patient_id" as patient_id,
    "practitioner_in_role_id" as practitioner_in_role_id,
    "schedule_id" as schedule_id,
    "start_date" as start_date,
    "planned_duration" as planned_duration,
    "actual_duration" as actual_duration,
    "appointment_status_concept_id" as appointment_status_concept_id,
    "patient_wait" as patient_wait,
    "patient_delay" as patient_delay,
    "date_time_booked" as date_time_booked,
    "date_time_sent_in" as date_time_sent_in,
    "date_time_left" as date_time_left,
    "cancelled_date" as cancelled_date,
    "type" as type,
    "age_at_event" as age_at_event,
    "age_at_event_baby" as age_at_event_baby,
    "age_at_event_neonate" as age_at_event_neonate,
    "booking_method_concept_id" as booking_method_concept_id,
    "contact_mode_concept_id" as contact_mode_concept_id,
    "is_blocked" as is_blocked,
    "national_slot_category_name" as national_slot_category_name,
    "context_type" as context_type,
    "service_setting" as service_setting,
    "national_slot_category_description" as national_slot_category_description,
    "csds_care_contact_identifier" as csds_care_contact_identifier,
    "person_id" as person_id
from {{ ref('base_olids_appointment') }}
