version: 2
models:
- name: base_olids_allergy_intolerance
  description: 'Filtered Allergy Intolerance base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_appointment
  description: 'Filtered Appointment base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_appointment_practitioner
  description: 'Filtered Appointment Practitioner base view.


    Applied filters:

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner join ensures only records with valid organisation references


    Filtering method: Inner join to int_ncl_practices on record_owner_organisation_code'
- name: base_olids_diagnostic_order
  description: 'Filtered Diagnostic Order base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_encounter
  description: 'Filtered Encounter base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_episode_of_care
  description: 'Filtered Episode Of Care base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_flag
  description: 'Filtered Flag base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_location
  description: 'Unfiltered Location reference view.


    No filters applied - reference data used as-is.

    Direct passthrough from source table with explicit column selection for interface consistency.'
- name: base_olids_location_contact
  description: 'Unfiltered Location Contact reference view.


    No filters applied - reference data used as-is.

    Direct passthrough from source table with explicit column selection for interface consistency.'
- name: base_olids_medication_order
  description: 'Filtered Medication Order base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_medication_statement
  description: 'Filtered Medication Statement base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_observation
  description: 'Filtered Observation base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_organisation
  description: 'Unfiltered Organisation reference view.


    No filters applied - reference data used as-is.

    Direct passthrough from source table with explicit column selection for interface consistency.'
- name: base_olids_patient
  description: "Base filtered patient view. Foundation for all patient-related filtering.\n\nExcludes sensitive patients:\n\
    - is_spine_sensitive = FALSE (excludes spine-sensitive patients)\n- is_confidential = FALSE (excludes confidential patients)\
    \ \n- is_dummy_patient = FALSE (excludes test/dummy patients)\n\nRestricts to NCL practices:\n- record_owner_organisation_code\
    \ IN (NCL practice codes with STPCode = 'QMJ')"
- name: base_olids_patient_address
  description: 'Filtered Patient Address base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_patient_contact
  description: 'Filtered Patient Contact base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_patient_person
  description: 'Generated Patient Person base view.


    Applied filters:

    - Patient filtering: Inherits filtering from underlying patient relationships

    - Practice filtering: Inherits NCL practice restriction through patient associations


    Filtering method: Filtered through relationships to base_olids_patient'
- name: base_olids_patient_registered_practitioner_in_role
  description: 'Filtered Patient Registered Practitioner In Role base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_patient_uprn
  description: 'Unfiltered Patient Uprn reference view.


    No filters applied - reference data used as-is.

    Direct passthrough from source table with explicit column selection for interface consistency.'
- name: base_olids_person
  description: 'Generated Person base view.


    Applied filters:

    - Patient filtering: Inherits filtering from underlying patient relationships

    - Practice filtering: Inherits NCL practice restriction through patient associations


    Filtering method: Filtered through relationships to base_olids_patient'
- name: base_olids_practitioner
  description: 'Filtered Practitioner base view.


    Applied filters:

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner join ensures only records with valid organisation references


    Filtering method: Inner join to int_ncl_practices on record_owner_organisation_code'
- name: base_olids_practitioner_in_role
  description: 'Filtered Practitioner In Role base view.


    Applied filters:

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner join ensures only records with valid organisation references


    Filtering method: Inner join to int_ncl_practices on record_owner_organisation_code'
- name: base_olids_procedure_request
  description: 'Filtered Procedure Request base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_referral_request
  description: 'Filtered Referral Request base view.


    Applied filters:

    - Patient filtering: Excludes sensitive patients (is_spine_sensitive=FALSE, is_confidential=FALSE, is_dummy_patient=FALSE)

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner joins ensure only records with valid patient and organisation references


    Filtering method: Inner join to base_olids_patient and int_ncl_practices'
- name: base_olids_schedule
  description: 'Filtered Schedule base view.


    Applied filters:

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner join ensures only records with valid organisation references


    Filtering method: Inner join to int_ncl_practices on record_owner_organisation_code'
- name: base_olids_schedule_practitioner
  description: 'Filtered Schedule Practitioner base view.


    Applied filters:

    - Practice filtering: Restricts to NCL practices only (STPCode = ''QMJ'')

    - Data integrity: Inner join ensures only records with valid organisation references


    Filtering method: Inner join to int_ncl_practices on record_owner_organisation_code'
- name: base_olids_terminology_concept
  description: 'Filtered Terminology Concept base view.


    Applied filters: Restricts data to NCL practices and excludes sensitive patients.

    Filtering method varies based on table structure and available foreign keys.'
- name: base_olids_terminology_concept_map
  description: 'Filtered Terminology Concept Map base view.


    Applied filters: Restricts data to NCL practices and excludes sensitive patients.

    Filtering method varies based on table structure and available foreign keys.'
