-- Staging model for RULESETS.EFI2_RULES
-- Source: "DATA_LAB_NCL_TRAINING_TEMP".RULESETS

SELECT
    "CODE" AS code,
    "DEFICIT" AS deficit,
    "DEFICIT_TYPE" AS deficit_type,
    "TIME_CONSTRAINT_DAYS" AS time_constraint_days,
    "TIME_CONSTRAINT_TYPE" AS time_constraint_type,
    "TIME_CONSTRAINT_DESCRIPTION" AS time_constraint_description,
    "MIN_AGE" AS min_age,
    "AGE_RESTRICTION_DESCRIPTION" AS age_restriction_description,
    "CATEGORY_NAME" AS category_name,
    "CATEGORY_ORDER" AS category_order,
    "CATEGORY_RANGE_START" AS category_range_start,
    "CATEGORY_RANGE_END" AS category_range_end,
    "CATEGORY_DESCRIPTION" AS category_description,
    "THRESHOLD_VALUE" AS threshold_value,
    "THRESHOLD_COMPARATOR" AS threshold_comparator,
    "THRESHOLD_DESCRIPTION" AS threshold_description,
    "THRESHOLD_UNIT" AS threshold_unit,
    "THRESHOLD_TYPE" AS threshold_type,
    "READINGS_REQUIRED" AS readings_required,
    "READINGS_TIMEFRAME" AS readings_timeframe,
    "SUPERSEDES" AS supersedes,
    "SUPERSEDED_BY" AS superseded_by,
    "HIERARCHY_LEVEL" AS hierarchy_level,
    "RESOLUTION_TEST" AS resolution_test,
    "RESOLUTION_THRESHOLD" AS resolution_threshold,
    "RESOLUTION_UNIT" AS resolution_unit,
    "RESOLUTION_GENDER_SPECIFIC" AS resolution_gender_specific,
    "RESOLUTION_MALE_THRESHOLD" AS resolution_male_threshold,
    "RESOLUTION_FEMALE_THRESHOLD" AS resolution_female_threshold,
    "VALIDATION_RULE" AS validation_rule,
    "VALIDATION_DESCRIPTION" AS validation_description,
    "EFI2_COEFFICIENT" AS efi2_coefficient,
    "EFI2_TRANSFORMED_COEFFICIENT" AS efi2_transformed_coefficient,
    "EFI_PLUS_FALLS_COEFFICIENT" AS efi_plus_falls_coefficient,
    "EFI_PLUS_CARE_HOME_COEFFICIENT" AS efi_plus_care_home_coefficient,
    "EFI_PLUS_MORTALITY_COEFFICIENT" AS efi_plus_mortality_coefficient,
    "EFI_PLUS_HOME_CARE_COEFFICIENT" AS efi_plus_home_care_coefficient,
    "SOURCE_INSTRUCTION" AS source_instruction,
    "RULE_PRIORITY" AS rule_priority
FROM {{ source('RULESETS', 'EFI2_RULES') }}
