-- Staging model for OLIDS_MASKED.MEDICATION_ORDER
-- Source: "Data_Store_OLIDS_Dummy".OLIDS_MASKED

select
    "lds_id" as lds_id,
    "id" as id,
    "lds_business_key" as lds_business_key,
    "record_owner_organisation_code" as record_owner_organisation_code,
    "lds_datetime_data_acquired" as lds_datetime_data_acquired,
    "lds_initial_data_received_date" as lds_initial_data_received_date,
    "lds_dataset_id" as lds_dataset_id,
    "organisation_id" as organisation_id,
    "person_id" as person_id,
    "patient_id" as patient_id,
    "medication_statement_id" as medication_statement_id,
    "encounter_id" as encounter_id,
    "practitioner_id" as practitioner_id,
    "observation_id" as observation_id,
    "allergy_intolerance_id" as allergy_intolerance_id,
    "diagnostic_order_id" as diagnostic_order_id,
    "referral_request_id" as referral_request_id,
    "clinical_effective_date" as clinical_effective_date,
    "date_precision_concept_id" as date_precision_concept_id,
    "dose" as dose,
    "quantity_value" as quantity_value,
    "quantity_unit" as quantity_unit,
    "duration_days" as duration_days,
    "estimated_cost" as estimated_cost,
    "medication_name" as medication_name,
    "medication_order_core_concept_id" as medication_order_core_concept_id,
    "bnf_reference" as bnf_reference,
    "age_at_event" as age_at_event,
    "age_at_event_baby" as age_at_event_baby,
    "age_at_event_neonate" as age_at_event_neonate,
    "issue_method" as issue_method,
    "date_recorded" as date_recorded,
    "is_confidential" as is_confidential,
    "lds_start_date_time" as lds_start_date_time,
    "lds_end_date_time" as lds_end_date_time
from {{ source('OLIDS_MASKED', 'MEDICATION_ORDER') }}
