CREATE OR REPLACE VIEW DATA_LAB_OLIDS_UAT.TESTS.TEST_MAPPED_CONCEPTS_TABLE_INTEGRITY AS
WITH TABLE_VALIDATION AS (
    -- Check for NULL SOURCE_CODE_ID
    SELECT
        'Data Integrity: NULL SOURCE_CODE_ID' AS VALIDATION_TYPE,
        'SOURCE_CODE_ID is a required field in MAPPED_CONCEPTS'
            AS VALIDATION_DESCRIPTION,
        COUNT(*) AS TOTAL_MAPPED_CONCEPTS,
        COUNT(DISTINCT SOURCE_CODE_ID) AS DISTINCT_SOURCE_CODES,
        COUNT(CASE WHEN SOURCE_CODE_ID IS NULL THEN 1 END)
            AS RECORDS_WITH_ISSUE,
        COUNT(CASE WHEN SOURCE_CODE_ID IS NULL THEN 1 END)
        = 0 AS VALIDATION_PASSED,
        'Records with NULL SOURCE_CODE_ID in MAPPED_CONCEPTS'
            AS ISSUE_DESCRIPTION
    FROM DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS

    UNION ALL

    -- Check for NULL CONCEPT_CODE
    SELECT
        'Data Integrity: NULL CONCEPT_CODE' AS VALIDATION_TYPE,
        'CONCEPT_CODE is a required field in MAPPED_CONCEPTS'
            AS VALIDATION_DESCRIPTION,
        COUNT(*) AS TOTAL_MAPPED_CONCEPTS,
        COUNT(DISTINCT SOURCE_CODE_ID) AS DISTINCT_SOURCE_CODES,
        COUNT(CASE WHEN CONCEPT_CODE IS NULL THEN 1 END) AS RECORDS_WITH_ISSUE,
        COUNT(CASE WHEN CONCEPT_CODE IS NULL THEN 1 END)
        = 0 AS VALIDATION_PASSED,
        'Records with NULL CONCEPT_CODE in MAPPED_CONCEPTS' AS ISSUE_DESCRIPTION
    FROM DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS

    UNION ALL

    -- Check for NULL CONCEPT_DISPLAY
    SELECT
        'Data Integrity: NULL CONCEPT_DISPLAY' AS VALIDATION_TYPE,
        'CONCEPT_DISPLAY is a required field in MAPPED_CONCEPTS'
            AS VALIDATION_DESCRIPTION,
        COUNT(*) AS TOTAL_MAPPED_CONCEPTS,
        COUNT(DISTINCT SOURCE_CODE_ID) AS DISTINCT_SOURCE_CODES,
        COUNT(CASE WHEN CONCEPT_DISPLAY IS NULL THEN 1 END)
            AS RECORDS_WITH_ISSUE,
        COUNT(CASE WHEN CONCEPT_DISPLAY IS NULL THEN 1 END)
        = 0 AS VALIDATION_PASSED,
        'Records with NULL CONCEPT_DISPLAY in MAPPED_CONCEPTS'
            AS ISSUE_DESCRIPTION
    FROM DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS

    UNION ALL

    -- Check that source codes exist in concept map
    SELECT
        'Referential Integrity: SOURCE_CODE_ID in CONCEPT_MAP'
            AS VALIDATION_TYPE,
        'All SOURCE_CODE_IDs in MAPPED_CONCEPTS should exist in CONCEPT_MAP'
            AS VALIDATION_DESCRIPTION,
        COUNT(*) AS TOTAL_MAPPED_CONCEPTS,
        COUNT(DISTINCT SOURCE_CODE_ID) AS DISTINCT_SOURCE_CODES,
        COUNT(CASE WHEN NOT EXISTS (
            SELECT 1
            FROM "Data_Store_OLIDS_Dummy".OLIDS_TERMINOLOGY.CONCEPT_MAP
            WHERE "source_code_id" = MAPPED_CONCEPTS.SOURCE_CODE_ID
        ) THEN 1 END) AS RECORDS_WITH_ISSUE,
        COUNT(CASE WHEN NOT EXISTS (
            SELECT 1
            FROM "Data_Store_OLIDS_Dummy".OLIDS_TERMINOLOGY.CONCEPT_MAP
            WHERE "source_code_id" = MAPPED_CONCEPTS.SOURCE_CODE_ID
        ) THEN 1 END) = 0 AS VALIDATION_PASSED,
        'Records in MAPPED_CONCEPTS with SOURCE_CODE_ID not found in CONCEPT_MAP'
            AS ISSUE_DESCRIPTION
    FROM DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS

    UNION ALL

    -- Check that mapped concepts exist in concept table
    SELECT
        'Referential Integrity: CONCEPT_CODE in CONCEPT' AS VALIDATION_TYPE,
        'All CONCEPT_CODEs in MAPPED_CONCEPTS should exist in CONCEPT'
            AS VALIDATION_DESCRIPTION,
        COUNT(*) AS TOTAL_MAPPED_CONCEPTS,
        COUNT(DISTINCT SOURCE_CODE_ID) AS DISTINCT_SOURCE_CODES,
        COUNT(CASE WHEN NOT EXISTS (
            SELECT 1
            FROM "Data_Store_OLIDS_Dummy".OLIDS_TERMINOLOGY.CONCEPT
            WHERE "code" = MAPPED_CONCEPTS.CONCEPT_CODE
        ) THEN 1 END) AS RECORDS_WITH_ISSUE,
        COUNT(CASE WHEN NOT EXISTS (
            SELECT 1
            FROM "Data_Store_OLIDS_Dummy".OLIDS_TERMINOLOGY.CONCEPT
            WHERE "code" = MAPPED_CONCEPTS.CONCEPT_CODE
        ) THEN 1 END) = 0 AS VALIDATION_PASSED,
        'Records in MAPPED_CONCEPTS with CONCEPT_CODE not found in CONCEPT'
            AS ISSUE_DESCRIPTION
    FROM DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS
)

SELECT
    VALIDATION_TYPE AS "Validation Type",
    VALIDATION_DESCRIPTION AS "Validation Description",
    TOTAL_MAPPED_CONCEPTS AS "Total Mapped Concepts",
    DISTINCT_SOURCE_CODES AS "Distinct Source Codes",
    RECORDS_WITH_ISSUE AS "Records with Issue",
    ISSUE_DESCRIPTION AS "Issue Description",
    VALIDATION_PASSED AS "Validation Passed",
    ROUND(RECORDS_WITH_ISSUE::FLOAT / TOTAL_MAPPED_CONCEPTS * 100, 2)
        AS "Percentage with Issue"
FROM TABLE_VALIDATION
ORDER BY VALIDATION_PASSED, VALIDATION_TYPE;
