CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_OLIDS_UAT.HEI_MIGRATION.FCT_PERSON_DX_HF (
    PERSON_ID VARCHAR, -- Unique identifier for the person
    SK_PATIENT_ID VARCHAR, -- Surrogate key for the patient
    AGE NUMBER, -- Age of the person
    IS_ON_HF_REGISTER BOOLEAN, -- Flag indicating if person is on the general unresolved Heart Failure register
    IS_ON_HF_LVSD_REDUCED_EF_REGISTER BOOLEAN, -- Flag for unresolved HF due to LVSD or Reduced Ejection Fraction

    EARLIEST_HF_DIAGNOSIS_DATE DATE, -- Earliest general Heart Failure diagnosis date
    LATEST_HF_DIAGNOSIS_DATE DATE, -- Latest general Heart Failure diagnosis date (HFLAT_DAT)
    LATEST_HF_RESOLVED_DATE_AFTER_LATEST_HF_DIAGNOSIS DATE, -- Latest HF resolved date that is after the LATEST_HF_DIAGNOSIS_DATE (HFRES_DAT)

    EARLIEST_HFLVSD_DIAGNOSIS_DATE DATE, -- Earliest HF due to LVSD diagnosis date
    LATEST_HFLVSD_DIAGNOSIS_DATE DATE, -- Latest HF due to LVSD diagnosis date
    HAS_LVSD_DIAGNOSIS BOOLEAN, -- Flag indicating if the person has an LVSD diagnosis

    EARLIEST_REDUCED_EF_DIAGNOSIS_DATE DATE, -- Earliest HF due to Reduced Ejection Fraction diagnosis date
    LATEST_REDUCED_EF_DIAGNOSIS_DATE DATE, -- Latest HF due to Reduced Ejection Fraction diagnosis date
    HAS_REDUCED_EF_DIAGNOSIS BOOLEAN, -- Flag indicating if the person has a Reduced Ejection Fraction diagnosis

    ALL_HF_CONCEPT_CODES ARRAY, -- All general HF concept codes
    ALL_HF_CONCEPT_DISPLAYS ARRAY, -- All general HF concept display terms
    ALL_HFRES_CONCEPT_CODES ARRAY, -- All HF resolved concept codes
    ALL_HFRES_CONCEPT_DISPLAYS ARRAY, -- All HF resolved concept display terms
    ALL_HFLVSD_CONCEPT_CODES ARRAY, -- All HF due to LVSD concept codes
    ALL_HFLVSD_CONCEPT_DISPLAYS ARRAY, -- All HF due to LVSD concept display terms
    ALL_REDEJCFRAC_CONCEPT_CODES ARRAY, -- All HF due to Reduced EF concept codes
    ALL_REDEJCFRAC_CONCEPT_DISPLAYS ARRAY -- All HF due to Reduced EF concept display terms
)
COMMENT = 'Fact table for Heart Failure, including general unresolved HF and HF due to LVSD or Reduced Ejection Fraction. Sources data from INTERMEDIATE_HF_DETAILS.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS

SELECT
    ihd.PERSON_ID,
    ihd.SK_PATIENT_ID,
    ihd.AGE,

    -- IS_ON_HF_REGISTER (BOOLEAN)
    (ihd.LATEST_HF_DIAGNOSIS_DATE IS NOT NULL AND
     CASE WHEN ihd.RAW_LATEST_HF_RESOLVED_DATE > ihd.LATEST_HF_DIAGNOSIS_DATE THEN ihd.RAW_LATEST_HF_RESOLVED_DATE ELSE NULL END IS NULL) AS IS_ON_HF_REGISTER,

    -- IS_ON_HF_LVSD_REDUCED_EF_REGISTER (BOOLEAN)
    (
      (ihd.LATEST_HF_DIAGNOSIS_DATE IS NOT NULL AND
       CASE WHEN ihd.RAW_LATEST_HF_RESOLVED_DATE > ihd.LATEST_HF_DIAGNOSIS_DATE THEN ihd.RAW_LATEST_HF_RESOLVED_DATE ELSE NULL END IS NULL)
      AND
      (ihd.EARLIEST_HFLVSD_DIAGNOSIS_DATE IS NOT NULL OR ihd.EARLIEST_REDUCED_EF_DIAGNOSIS_DATE IS NOT NULL)
    ) AS IS_ON_HF_LVSD_REDUCED_EF_REGISTER,

    -- EARLIEST_HF_DIAGNOSIS_DATE
    ihd.EARLIEST_HF_DIAGNOSIS_DATE,
    -- LATEST_HF_DIAGNOSIS_DATE
    ihd.LATEST_HF_DIAGNOSIS_DATE,
    -- LATEST_HF_RESOLVED_DATE_AFTER_LATEST_HF_DIAGNOSIS (DATE)
    CASE
        WHEN ihd.RAW_LATEST_HF_RESOLVED_DATE > ihd.LATEST_HF_DIAGNOSIS_DATE THEN ihd.RAW_LATEST_HF_RESOLVED_DATE
        ELSE NULL
    END AS LATEST_HF_RESOLVED_DATE_AFTER_LATEST_HF_DIAGNOSIS,

    -- EARLIEST_HFLVSD_DIAGNOSIS_DATE
    ihd.EARLIEST_HFLVSD_DIAGNOSIS_DATE,
    -- LATEST_HFLVSD_DIAGNOSIS_DATE
    ihd.LATEST_HFLVSD_DIAGNOSIS_DATE,
    -- HAS_LVSD_DIAGNOSIS (BOOLEAN)
    (ihd.EARLIEST_HFLVSD_DIAGNOSIS_DATE IS NOT NULL) AS HAS_LVSD_DIAGNOSIS,

    -- EARLIEST_REDUCED_EF_DIAGNOSIS_DATE
    ihd.EARLIEST_REDUCED_EF_DIAGNOSIS_DATE,
    -- LATEST_REDUCED_EF_DIAGNOSIS_DATE
    ihd.LATEST_REDUCED_EF_DIAGNOSIS_DATE,
    -- HAS_REDUCED_EF_DIAGNOSIS (BOOLEAN)
    (ihd.EARLIEST_REDUCED_EF_DIAGNOSIS_DATE IS NOT NULL) AS HAS_REDUCED_EF_DIAGNOSIS,

    -- ALL_HF_CONCEPT_CODES
    ihd.ALL_HF_CONCEPT_CODES,
    ihd.ALL_HF_CONCEPT_DISPLAYS,
    ihd.ALL_HFRES_CONCEPT_CODES,
    ihd.ALL_HFRES_CONCEPT_DISPLAYS,
    ihd.ALL_HFLVSD_CONCEPT_CODES,
    ihd.ALL_HFLVSD_CONCEPT_DISPLAYS,
    ihd.ALL_REDEJCFRAC_CONCEPT_CODES,
    ihd.ALL_REDEJCFRAC_CONCEPT_DISPLAYS
FROM DATA_LAB_OLIDS_UAT.HEI_MIGRATION.INTERMEDIATE_HF_DETAILS ihd
WHERE ihd.LATEST_HF_DIAGNOSIS_DATE IS NOT NULL; -- Rule 1: HFLAT_DAT != Null (Latest HF diagnosis must exist for consideration)
