version: 2

# Seed configurations have been removed as part of the unsafe introspection fix
# The seed CSV files remain in the project for reference but are no longer used by dbt
# All configuration is now handled through static definitions in:
# - macros/flu/flu_campaign_utils.sql (for macro usage)
# - models/staging/stg_flu_*.sql (for staging table generation)
#
# This eliminates the dbt1000 warning about unsafe introspection while maintaining
# the same functionality with a single source of truth.

seeds: []