{{
    config(
        materialized='table',
        tags=['dimension', 'person', 'active'],
        cluster_by=['person_id'],
        post_hook=[
            "COMMENT ON TABLE {{ this }} IS 'Dimension table providing active patient status at person level. Uses proper registration data from episode_of_care to determine current practice. Excludes deceased patients and dummy patients.

🤖 Generated by dbt. This table is managed by dbt - for model definitions and documentation, see https://github.com/ncl-icb-analytics/snowflake-hei-migration'"
        ]
    )
}}

-- Person Active Patients Dimension Table
-- Now uses proper registration data from episode_of_care via int_patient_registrations
-- Filters out deceased patients and dummy patients
-- Links PATIENT_PERSON, PATIENT, PERSON, and proper registration data

WITH patient_ids_per_person AS (
    -- First collect all patient IDs for each person
    SELECT
        pp.person_id,
        ARRAY_AGG(DISTINCT pp.patient_id) WITHIN GROUP (
            ORDER BY pp.patient_id
        ) AS patient_ids
    FROM {{ ref('stg_olids_patient_person') }} AS pp
    GROUP BY pp.person_id
),

current_registrations AS (
    -- Get current registration details per person
    SELECT
        ipr.person_id,
        ipr.organisation_id AS current_practice_id,
        ipr.practice_name AS current_practice_name,
        ipr.practice_ods_code AS current_practice_code,
        ipr.registration_start_date AS current_registration_start,
        ipr.registration_duration_days AS current_registration_duration,
        ipr.total_registrations_count,
        ipr.has_changed_practice,
        -- Additional registration metadata
        ipr.care_manager_practitioner_id
    FROM {{ ref('int_patient_registrations') }} AS ipr
    WHERE ipr.is_current_registration = TRUE
),

latest_patient_record_per_person AS (
    -- Get the latest patient record for each person with registration details
    SELECT
        pp.person_id,
        p.sk_patient_id,
        per.ldsbusinessid_primarypatient,
        pip.patient_ids,
        -- Determine if patient is active based on various criteria
        p.is_dummy_patient,
        p.is_confidential,
        p.is_spine_sensitive,
        p.birth_year,
        p.birth_month,
        p.death_year,
        p.death_month,
        cr.current_practice_id,
        cr.current_practice_code,
        -- Registration details from proper episode_of_care data
        cr.current_practice_name,
        cr.current_registration_start,
        cr.current_registration_duration,
        cr.total_registrations_count,
        cr.has_changed_practice,
        cr.care_manager_practitioner_id,
        p.record_owner_organisation_code AS record_owner_org_code,
        p.lds_datetime_data_acquired AS latest_record_date,
        CASE
            WHEN p.death_year IS NOT NULL THEN FALSE -- Deceased
            WHEN p.is_dummy_patient THEN FALSE -- Dummy patient
            WHEN cr.person_id IS NULL THEN FALSE -- No current registration
            ELSE TRUE
        END AS is_active,
        p.death_year IS NOT NULL AS is_deceased,
        -- Rank to get the latest record
        ROW_NUMBER() OVER (
            PARTITION BY pp.person_id
            ORDER BY
                p.lds_datetime_data_acquired DESC,
                p.id DESC
        ) AS record_rank
    FROM {{ ref('stg_olids_patient_person') }} AS pp
    INNER JOIN {{ ref('stg_olids_patient') }} AS p
        ON pp.patient_id = p.id
    INNER JOIN {{ ref('stg_olids_person') }} AS per
        ON pp.person_id = per.id
    INNER JOIN patient_ids_per_person AS pip
        ON pp.person_id = pip.person_id
    LEFT JOIN current_registrations AS cr
        ON pp.person_id = cr.person_id
)

-- Select only the latest record per person and only active patients
SELECT
    person_id,
    sk_patient_id,
    ldsbusinessid_primarypatient,
    patient_ids,
    is_active,
    is_deceased,
    is_dummy_patient,
    is_confidential,
    is_spine_sensitive,
    birth_year,
    birth_month,
    death_year,
    death_month,
    -- Registration-based practice information
    current_practice_id,
    current_practice_code,
    current_practice_name,
    current_registration_start,
    current_registration_duration,
    total_registrations_count,
    has_changed_practice,
    care_manager_practitioner_id,
    record_owner_org_code,
    latest_record_date
FROM latest_patient_record_per_person
WHERE
    record_rank = 1
    AND is_active = TRUE
