CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PRACTICE_NEIGHBOURHOOD (
    PRACTICE_CODE VARCHAR COMMENT 'Practice organisation code',
    PRACTICE_NAME VARCHAR COMMENT 'Name of the practice',
    LOCAL_AUTHORITY VARCHAR COMMENT 'Local authority area',
    PRACTICE_NEIGHBOURHOOD VARCHAR COMMENT 'Practice neighbourhood classification'
)
COMMENT = 'Dimension table providing practice neighbourhood information. Sources from PRACTICE_NEIGHBOURHOOD_LOOKUP in the POPULATION_HEALTH schema. PCN information is available separately in DIM_PRACTICE_PCN.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT
    pnl.PRACTICECODE AS PRACTICE_CODE,
    pnl.PRACTICENAME AS PRACTICE_NAME,
    pnl.LOCALAUTHORITY AS LOCAL_AUTHORITY,
    pnl.PRACTICENEIGHBOURHOOD AS PRACTICE_NEIGHBOURHOOD
FROM DATA_LAB_NCL_TRAINING_TEMP.POPULATION_HEALTH.PRACTICE_NEIGHBOURHOOD_LOOKUP pnl;
