CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_MOC_BASE (
    PERSON_ID VARCHAR, -- Unique identifier for the person
    SK_PATIENT_ID VARCHAR, -- Surrogate key for the patient
    AGE NUMBER, -- Age of the patient
    -- Condition flags
    HAS_ASTHMA BOOLEAN, -- Flag indicating if person has asthma
    HAS_AF BOOLEAN, -- Flag indicating if person has atrial fibrillation
    HAS_CKD BOOLEAN, -- Flag indicating if person has chronic kidney disease
    HAS_COPD BOOLEAN, -- Flag indicating if person has COPD
    HAS_CHD BOOLEAN, -- Flag indicating if person has coronary heart disease
    HAS_DIABETES BOOLEAN, -- Flag indicating if person has diabetes
    HAS_HEART_FAILURE BOOLEAN, -- Flag indicating if person has heart failure
    HAS_HYPERTENSION BOOLEAN, -- Flag indicating if person has hypertension
    HAS_PAD BOOLEAN, -- Flag indicating if person has peripheral arterial disease
    HAS_STROKE_TIA BOOLEAN, -- Flag indicating if person has stroke/TIA
    HAS_NAFLD BOOLEAN, -- Flag indicating if person has non-alcoholic fatty liver disease
    -- Earliest diagnosis dates
    EARLIEST_ASTHMA_DATE DATE, -- Earliest asthma diagnosis date
    EARLIEST_AF_DATE DATE, -- Earliest AF diagnosis date
    EARLIEST_CKD_DATE DATE, -- Earliest CKD diagnosis date
    EARLIEST_COPD_DATE DATE, -- Earliest COPD diagnosis date
    EARLIEST_CHD_DATE DATE, -- Earliest CHD diagnosis date
    EARLIEST_DIABETES_DATE DATE, -- Earliest diabetes diagnosis date
    EARLIEST_HEART_FAILURE_DATE DATE, -- Earliest heart failure diagnosis date
    EARLIEST_HYPERTENSION_DATE DATE, -- Earliest hypertension diagnosis date
    EARLIEST_PAD_DATE DATE, -- Earliest PAD diagnosis date
    EARLIEST_STROKE_TIA_DATE DATE, -- Earliest stroke/TIA diagnosis date
    EARLIEST_NAFLD_DATE DATE, -- Earliest NAFLD diagnosis date
    -- Latest diagnosis dates
    LATEST_ASTHMA_DATE DATE, -- Latest asthma diagnosis date
    LATEST_AF_DATE DATE, -- Latest AF diagnosis date
    LATEST_CKD_DATE DATE, -- Latest CKD diagnosis date
    LATEST_COPD_DATE DATE, -- Latest COPD diagnosis date
    LATEST_CHD_DATE DATE, -- Latest CHD diagnosis date
    LATEST_DIABETES_DATE DATE, -- Latest diabetes diagnosis date
    LATEST_HEART_FAILURE_DATE DATE, -- Latest heart failure diagnosis date
    LATEST_HYPERTENSION_DATE DATE, -- Latest hypertension diagnosis date
    LATEST_PAD_DATE DATE, -- Latest PAD diagnosis date
    LATEST_STROKE_TIA_DATE DATE, -- Latest stroke/TIA diagnosis date
    LATEST_NAFLD_DATE DATE, -- Latest NAFLD diagnosis date
    -- Summary fields
    TOTAL_CONDITIONS NUMBER, -- Total number of conditions
    ALL_CONDITION_CODES ARRAY, -- Array of all condition codes
    ALL_CONDITION_NAMES ARRAY -- Array of all condition names
)
COMMENT = 'Base population dimension table for the LTC LCS model of care. Includes patients with any of the following conditions: Asthma, Atrial Fibrillation, Chronic Kidney Disease, COPD, Coronary Heart Disease, Diabetes, Heart Failure, Hypertension, Peripheral Arterial Disease, Stroke/TIA, or Non-Alcoholic Fatty Liver Disease.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH ConditionSummary AS (
    -- Get all relevant conditions from LTC summary
    SELECT
        PERSON_ID,
        SK_PATIENT_ID,
        CONDITION_CODE,
        CONDITION_NAME,
        EARLIEST_DIAGNOSIS_DATE,
        LATEST_DIAGNOSIS_DATE,
        IS_ON_REGISTER
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.FCT_PERSON_LTC_SUMMARY
    WHERE CONDITION_CODE IN ('AST', 'AF', 'CKD', 'COPD', 'CHD', 'DM', 'HF', 'HTN', 'PAD', 'STIA', 'NAF')
        AND IS_ON_REGISTER = TRUE
),
PersonAge AS (
    -- Get person age
    SELECT
        PERSON_ID,
        AGE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_AGE
),
ConditionPivot AS (
    -- Pivot conditions to get one row per person with all condition flags and dates
    SELECT
        PERSON_ID,
        SK_PATIENT_ID,
        -- Condition flags
        MAX(CASE WHEN CONDITION_CODE = 'AST' THEN TRUE ELSE FALSE END) AS HAS_ASTHMA,
        MAX(CASE WHEN CONDITION_CODE = 'AF' THEN TRUE ELSE FALSE END) AS HAS_AF,
        MAX(CASE WHEN CONDITION_CODE = 'CKD' THEN TRUE ELSE FALSE END) AS HAS_CKD,
        MAX(CASE WHEN CONDITION_CODE = 'COPD' THEN TRUE ELSE FALSE END) AS HAS_COPD,
        MAX(CASE WHEN CONDITION_CODE = 'CHD' THEN TRUE ELSE FALSE END) AS HAS_CHD,
        MAX(CASE WHEN CONDITION_CODE = 'DM' THEN TRUE ELSE FALSE END) AS HAS_DIABETES,
        MAX(CASE WHEN CONDITION_CODE = 'HF' THEN TRUE ELSE FALSE END) AS HAS_HEART_FAILURE,
        MAX(CASE WHEN CONDITION_CODE = 'HTN' THEN TRUE ELSE FALSE END) AS HAS_HYPERTENSION,
        MAX(CASE WHEN CONDITION_CODE = 'PAD' THEN TRUE ELSE FALSE END) AS HAS_PAD,
        MAX(CASE WHEN CONDITION_CODE = 'STIA' THEN TRUE ELSE FALSE END) AS HAS_STROKE_TIA,
        MAX(CASE WHEN CONDITION_CODE = 'NAF' THEN TRUE ELSE FALSE END) AS HAS_NAFLD,
        -- Earliest diagnosis dates
        MIN(CASE WHEN CONDITION_CODE = 'AST' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_ASTHMA_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'AF' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_AF_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'CKD' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_CKD_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'COPD' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_COPD_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'CHD' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_CHD_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'DM' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_DIABETES_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'HF' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_HEART_FAILURE_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'HTN' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_HYPERTENSION_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'PAD' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_PAD_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'STIA' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_STROKE_TIA_DATE,
        MIN(CASE WHEN CONDITION_CODE = 'NAF' THEN EARLIEST_DIAGNOSIS_DATE END) AS EARLIEST_NAFLD_DATE,
        -- Latest diagnosis dates
        MAX(CASE WHEN CONDITION_CODE = 'AST' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_ASTHMA_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'AF' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_AF_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'CKD' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_CKD_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'COPD' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_COPD_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'CHD' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_CHD_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'DM' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_DIABETES_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'HF' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_HEART_FAILURE_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'HTN' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_HYPERTENSION_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'PAD' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_PAD_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'STIA' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_STROKE_TIA_DATE,
        MAX(CASE WHEN CONDITION_CODE = 'NAF' THEN LATEST_DIAGNOSIS_DATE END) AS LATEST_NAFLD_DATE,
        -- Arrays of all conditions
        ARRAY_AGG(DISTINCT CONDITION_CODE) AS ALL_CONDITION_CODES,
        ARRAY_AGG(DISTINCT CONDITION_NAME) AS ALL_CONDITION_NAMES,
        -- Total conditions count
        COUNT(DISTINCT CONDITION_CODE) AS TOTAL_CONDITIONS
    FROM ConditionSummary
    GROUP BY PERSON_ID, SK_PATIENT_ID
)
-- Final selection
SELECT
    cp.PERSON_ID,
    cp.SK_PATIENT_ID,
    pa.AGE,
    cp.HAS_ASTHMA,
    cp.HAS_AF,
    cp.HAS_CKD,
    cp.HAS_COPD,
    cp.HAS_CHD,
    cp.HAS_DIABETES,
    cp.HAS_HEART_FAILURE,
    cp.HAS_HYPERTENSION,
    cp.HAS_PAD,
    cp.HAS_STROKE_TIA,
    cp.HAS_NAFLD,
    cp.EARLIEST_ASTHMA_DATE,
    cp.EARLIEST_AF_DATE,
    cp.EARLIEST_CKD_DATE,
    cp.EARLIEST_COPD_DATE,
    cp.EARLIEST_CHD_DATE,
    cp.EARLIEST_DIABETES_DATE,
    cp.EARLIEST_HEART_FAILURE_DATE,
    cp.EARLIEST_HYPERTENSION_DATE,
    cp.EARLIEST_PAD_DATE,
    cp.EARLIEST_STROKE_TIA_DATE,
    cp.EARLIEST_NAFLD_DATE,
    cp.LATEST_ASTHMA_DATE,
    cp.LATEST_AF_DATE,
    cp.LATEST_CKD_DATE,
    cp.LATEST_COPD_DATE,
    cp.LATEST_CHD_DATE,
    cp.LATEST_DIABETES_DATE,
    cp.LATEST_HEART_FAILURE_DATE,
    cp.LATEST_HYPERTENSION_DATE,
    cp.LATEST_PAD_DATE,
    cp.LATEST_STROKE_TIA_DATE,
    cp.LATEST_NAFLD_DATE,
    cp.TOTAL_CONDITIONS,
    cp.ALL_CONDITION_CODES,
    cp.ALL_CONDITION_NAMES
FROM ConditionPivot cp
JOIN PersonAge pa
    USING (PERSON_ID);
