CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_OLIDS_UAT.HEI_MIGRATION.DIM_PROG_VALPROATE_ARAF_REFERRAL (
    PERSON_ID VARCHAR COMMENT 'Unique identifier for the person',
    SK_PATIENT_ID VARCHAR COMMENT 'Surrogate key for the patient',
    HAS_ARAF_REFERRAL_EVENT BOOLEAN COMMENT 'Always TRUE, indicating at least one ARAF referral event meeting criteria',
    EARLIEST_ARAF_REFERRAL_EVENT_DATE DATE COMMENT 'Earliest date of any ARAF referral event for the person',
    LATEST_ARAF_REFERRAL_EVENT_DATE DATE COMMENT 'Latest date of any ARAF referral event for the person',
    ALL_ARAF_REFERRAL_OBSERVATION_IDS ARRAY COMMENT 'Array of unique observation IDs related to ARAF referral events',
    ALL_ARAF_REFERRAL_CONCEPT_CODES ARRAY COMMENT 'Array of all distinct ARAF referral medical concept codes found',
    ALL_ARAF_REFERRAL_CONCEPT_DISPLAYS ARRAY COMMENT 'Array of display terms for the ARAF referral codes (from MAPPED_CONCEPTS.CODE_DESCRIPTION)',
    ALL_ARAF_REFERRAL_CODE_CATEGORIES_APPLIED ARRAY COMMENT 'Array of code categories applied (will contain \'-REFERRAL\'-)'
)
COMMENT = 'Dimension table aggregating ARAF referral events for each person, using MAPPED_CONCEPTS, OBSERVATION, and VALPROATE_PROG_CODES (category REFERRAL).'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH BaseARAFReferralObservations AS (
    -- Selects ARAF referral-related observations.
    -- LOOKBACK_YEARS_OFFSET is NULL for all REFERRAL codes, so all historical records are considered.
    SELECT
        PP."person_id" AS PERSON_ID,
        PAT."sk_patient_id" AS SK_PATIENT_ID,
        O."id" AS OBSERVATION_ID,
        O."clinical_effective_date"::DATE AS ARAF_REFERRAL_EVENT_DATE,
        MC.CONCEPT_CODE AS ARAF_REFERRAL_CONCEPT_CODE,
        MC.CODE_DESCRIPTION AS ARAF_REFERRAL_CONCEPT_DISPLAY,
        VPC.CODE_CATEGORY AS ARAF_REFERRAL_CODE_CATEGORY -- This will be 'REFERRAL'
    FROM
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" AS O
    JOIN
        DATA_LAB_OLIDS_UAT.REFERENCE.MAPPED_CONCEPTS AS MC
        ON O."observation_core_concept_id" = MC.SOURCE_CODE_ID
    JOIN
        DATA_LAB_OLIDS_UAT.REFERENCE.VALPROATE_PROG_CODES AS VPC
        ON MC.CONCEPT_CODE = VPC.CODE
    JOIN
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT_PERSON" AS PP
        ON O."patient_id" = PP."patient_id"
    JOIN
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT" AS PAT
        ON PP."patient_id" = PAT."id"
    WHERE
        VPC.CODE_CATEGORY = 'REFERRAL'
        AND (
            VPC.LOOKBACK_YEARS_OFFSET IS NULL OR
            O."clinical_effective_date"::DATE >= DATEADD(YEAR, VPC.LOOKBACK_YEARS_OFFSET, CURRENT_DATE())
        )
),
PersonLevelARAFReferralAggregation AS (
    -- Aggregates ARAF referral information for each person.
    SELECT
        PERSON_ID,
        ANY_VALUE(SK_PATIENT_ID) as SK_PATIENT_ID,
        MIN(ARAF_REFERRAL_EVENT_DATE) AS EARLIEST_ARAF_REFERRAL_EVENT_DATE,
        MAX(ARAF_REFERRAL_EVENT_DATE) AS LATEST_ARAF_REFERRAL_EVENT_DATE,
        ARRAY_AGG(DISTINCT OBSERVATION_ID) WITHIN GROUP (ORDER BY OBSERVATION_ID) AS ALL_ARAF_REFERRAL_OBSERVATION_IDS,
        ARRAY_AGG(DISTINCT ARAF_REFERRAL_CONCEPT_CODE) WITHIN GROUP (ORDER BY ARAF_REFERRAL_CONCEPT_CODE) AS ALL_ARAF_REFERRAL_CONCEPT_CODES,
        ARRAY_AGG(DISTINCT ARAF_REFERRAL_CONCEPT_DISPLAY) WITHIN GROUP (ORDER BY ARAF_REFERRAL_CONCEPT_DISPLAY) AS ALL_ARAF_REFERRAL_CONCEPT_DISPLAYS,
        ARRAY_AGG(DISTINCT ARAF_REFERRAL_CODE_CATEGORY) WITHIN GROUP (ORDER BY ARAF_REFERRAL_CODE_CATEGORY) AS ALL_ARAF_REFERRAL_CODE_CATEGORIES_APPLIED
    FROM BaseARAFReferralObservations
    GROUP BY PERSON_ID
)
SELECT
    pla.PERSON_ID,
    pla.SK_PATIENT_ID,
    TRUE AS HAS_ARAF_REFERRAL_EVENT,
    pla.EARLIEST_ARAF_REFERRAL_EVENT_DATE,
    pla.LATEST_ARAF_REFERRAL_EVENT_DATE,
    pla.ALL_ARAF_REFERRAL_OBSERVATION_IDS,
    pla.ALL_ARAF_REFERRAL_CONCEPT_CODES,
    pla.ALL_ARAF_REFERRAL_CONCEPT_DISPLAYS,
    pla.ALL_ARAF_REFERRAL_CODE_CATEGORIES_APPLIED
FROM PersonLevelARAFReferralAggregation pla;
