CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_OLIDS_UAT.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_66 (
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    NEEDS_STATIN_REVIEW BOOLEAN,
    LATEST_QRISK2_DATE DATE,
    LATEST_QRISK2_VALUE NUMBER,
    ALL_QRISK2_CODES ARRAY,
    ALL_QRISK2_DISPLAYS ARRAY
)
COMMENT = 'Dimension table for LTC LCS case finding indicator CVD_66: Patients aged 75-83 who need a statin review. Identifies patients from the base population who have no recent QRISK2 assessment. Only includes patients who meet all criteria.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH QRISK2Readings AS (
    -- Get all QRISK2 readings with values > 0
    SELECT
        PERSON_ID,
        SK_PATIENT_ID,
        CLINICAL_EFFECTIVE_DATE,
        RESULT_VALUE,
        CONCEPT_CODE,
        CONCEPT_DISPLAY
    FROM DATA_LAB_OLIDS_UAT.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_RAW_DATA
    WHERE CLUSTER_ID = 'QRISK2_10YEAR'
        AND RESULT_VALUE > 0
),
QRISK2Ranked AS (
    -- Rank QRISK2 readings by date for each person
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY PERSON_ID ORDER BY CLINICAL_EFFECTIVE_DATE DESC) AS READING_RANK
    FROM QRISK2Readings
    QUALIFY READING_RANK = 1
),
QRISK2Codes AS (
    -- Get all codes and displays for each person
    SELECT
        PERSON_ID,
        ARRAY_AGG(DISTINCT CONCEPT_CODE) WITHIN GROUP (ORDER BY CONCEPT_CODE) AS ALL_QRISK2_CODES,
        ARRAY_AGG(DISTINCT CONCEPT_DISPLAY) WITHIN GROUP (ORDER BY CONCEPT_DISPLAY) AS ALL_QRISK2_DISPLAYS
    FROM QRISK2Readings
    GROUP BY PERSON_ID
)
-- Final selection
SELECT
    bp.PERSON_ID,
    bp.SK_PATIENT_ID,
    bp.AGE,
    CASE
        WHEN qr.PERSON_ID IS NULL THEN TRUE  -- No QRISK2 assessment
        ELSE FALSE
    END AS NEEDS_STATIN_REVIEW,
    qr.CLINICAL_EFFECTIVE_DATE AS LATEST_QRISK2_DATE,
    qr.RESULT_VALUE AS LATEST_QRISK2_VALUE,
    codes.ALL_QRISK2_CODES,
    codes.ALL_QRISK2_DISPLAYS
FROM DATA_LAB_OLIDS_UAT.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_CVD_66_BASE bp
LEFT JOIN QRISK2Ranked qr
    USING (PERSON_ID)
LEFT JOIN QRISK2Codes codes
    USING (PERSON_ID)
WHERE qr.PERSON_ID IS NULL;  -- Only include patients with no QRISK2 assessment
