CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_65 (
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    NEEDS_MODERATE_DOSE_STATIN BOOLEAN,
    LATEST_QRISK2_DATE DATE,
    LATEST_QRISK2_VALUE NUMBER,
    ALL_QRISK2_CODES ARRAY,
    ALL_QRISK2_DISPLAYS ARRAY
)
COMMENT = 'Dimension table for CVD 65 case finding indicator. Identifies patients with QRISK2 ≥ 10 who need moderate-dose statins (not on moderate-dose statins, no allergies, no decisions).'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH QRISK2Readings AS (
    -- Get all QRISK2 readings for patients in base
    SELECT
        r.PERSON_ID,
        r.SK_PATIENT_ID,
        r.CLINICAL_EFFECTIVE_DATE,
        r.RESULT_VALUE,
        r.CONCEPT_CODE,
        r.CONCEPT_DISPLAY,
        ROW_NUMBER() OVER (PARTITION BY r.PERSON_ID ORDER BY r.CLINICAL_EFFECTIVE_DATE DESC) AS rn
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_RAW_DATA r
    JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_CVD_65_BASE b
        ON r.PERSON_ID = b.PERSON_ID
    WHERE r.CLUSTER_ID = 'QRISK2_10YEAR'
        AND r.RESULT_VALUE >= 10
),
QRISK2Aggregated AS (
    -- Aggregate all QRISK2 codes and displays
    SELECT
        PERSON_ID,
        ARRAY_AGG(CONCEPT_CODE) AS ALL_QRISK2_CODES,
        ARRAY_AGG(CONCEPT_DISPLAY) AS ALL_QRISK2_DISPLAYS
    FROM QRISK2Readings
    GROUP BY PERSON_ID
)
-- Final selection
SELECT
    b.PERSON_ID,
    b.SK_PATIENT_ID,
    b.AGE,
    TRUE AS NEEDS_MODERATE_DOSE_STATIN,  -- All patients in base need moderate dose statins
    qr.CLINICAL_EFFECTIVE_DATE AS LATEST_QRISK2_DATE,
    qr.RESULT_VALUE AS LATEST_QRISK2_VALUE,
    qa.ALL_QRISK2_CODES,
    qa.ALL_QRISK2_DISPLAYS
FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_CVD_65_BASE b
JOIN QRISK2Readings qr
    ON b.PERSON_ID = qr.PERSON_ID
    AND qr.rn = 1  -- Get most recent reading
LEFT JOIN QRISK2Aggregated qa
    ON b.PERSON_ID = qa.PERSON_ID;
