WITH RESULTS AS (
SELECT * FROM

(SELECT DISTINCT B.EMPI_ID, 
ROW_NUMBER () OVER (PARTITION BY B.EMPI_ID, R.SOURCE_DESCRIPTION, CLUSTER_ID ORDER BY R.SERVICE_DATE DESC, NORM_NUMERIC_VALUE DESC) AS Row_Num,
NORM_NUMERIC_VALUE AS Value,
CLUSTER_ID, RESULT_CODE, R.SOURCE_DESCRIPTION, B.EMIS, B.OTHER

FROM ICB_CF_HTN_61_BASE AS B
INNER JOIN PH_F_RESULT AS R ON B.EMPI_ID = R.EMPI_ID
INNER JOIN JOINED_LTC_LOOKUP AS T ON T.SNOMED_CODE = R.RESULT_CODE

WHERE T.CLUSTER_ID IN ('HTN_SYSTOLIC_1','HTN_DIASTOLIC_1')
AND R.NORM_NUMERIC_VALUE >0
AND DATE(R.SERVICE_DATE) <= CURRENT_DATE()) AS Results

WHERE Row_Num = '1'

)

-- Creating CTE for EMIS sourced
,EMIS AS ( 

SELECT DISTINCT A.EMPI_ID, 1 as 'EMIS'  

FROM
( 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE EMIS = '1' AND SOURCE_DESCRIPTION = 'EMIS GP' AND 
R.CLUSTER_ID = 'HTN_SYSTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_SYSTOLIC_2' AND
Value >= 180

UNION

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE EMIS = '1' AND SOURCE_DESCRIPTION = 'EMIS GP' AND 
R.CLUSTER_ID = 'HTN_DIASTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_DIASTOLIC_2' AND
Value >= 120

UNION 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE EMIS = '1' AND SOURCE_DESCRIPTION = 'EMIS GP' AND 
R.CLUSTER_ID = 'HTN_SYSTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_AMBULATORY_SYSTOLIC' AND
Value >= 170

UNION 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE EMIS = '1' AND SOURCE_DESCRIPTION = 'EMIS GP' AND 
R.CLUSTER_ID = 'HTN_DIASTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_AMBULATORY_DIASTOLIC' AND 
Value >= 115

) AS A

)

-- Creating CTE for all sources
,OTHER AS ( 

SELECT DISTINCT A.EMPI_ID, 1 as OTHER 

FROM
( 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE 
R.CLUSTER_ID = 'HTN_SYSTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_SYSTOLIC_2' AND
Value >= 180

UNION

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE 
R.CLUSTER_ID = 'HTN_DIASTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_DIASTOLIC_2' AND
Value >= 120

UNION 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE
R.CLUSTER_ID = 'HTN_SYSTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_AMBULATORY_SYSTOLIC' AND
Value >= 170

UNION 

SELECT DISTINCT R.EMPI_ID 

FROM RESULTS AS R
INNER JOIN JOINED_LTC_LOOKUP AS L ON R.RESULT_CODE = L.SNOMED_CODE 

WHERE 
R.CLUSTER_ID = 'HTN_DIASTOLIC_1' AND 
L.CLUSTER_ID = 'HTN_AMBULATORY_DIASTOLIC' AND 
Value >= 115

) AS A

)

-- USING 'OTHER' TABLE TO GET WHOLE COHORT AND LEFT JOINING TO SEE WHETHER THEY ARE EMIS SOURCED OR NOT
SELECT 
COALESCE(e.empi_id, o.empi_id) as empi_id,
case when e.EMIS = 1 then 'EMIS' else 'Other' end as SOURCE
FROM EMIS e
FULL OUTER JOIN OTHER o USING (empi_id)