-- CTE for OTHER source
WITH OTHER AS (
    SELECT EMPI_ID 
    FROM ICB_CF_CVD_63_BASE
    EXCEPT 
    SELECT EMPI_ID
    FROM CERNER_MEDICATION_JOINED_TABLE
    WHERE DRUG_CODE IN (
        SELECT SNOMED_CODE
        FROM JOINED_LTC_LOOKUP
        WHERE CLUSTER_ID = 'STAT_COD'
    )
    AND START_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)
    EXCEPT
    SELECT EMPI_ID
    FROM NCL_CODES
    WHERE CODE IN (
        SELECT SNOMED_CODE
        FROM JOINED_LTC_LOOKUP
        WHERE CLUSTER_ID IN ('STATINDEC_COD')
    )
    AND DATETIME >= ADD_MONTHS(CURRENT_DATE(), -60)
),
-- CTE for EMIS source
EMIS AS (
    SELECT EMPI_ID 
    FROM ICB_CF_CVD_63_BASE
    EXCEPT 
    SELECT EMPI_ID
    FROM CERNER_MEDICATION_JOINED_TABLE
    WHERE DRUG_CODE IN (
        SELECT SNOMED_CODE
        FROM JOINED_LTC_LOOKUP
        WHERE CLUSTER_ID = 'STAT_COD'
    )
    AND START_DT_TM >= ADD_MONTHS(CURRENT_DATE(), -12)
    AND SOURCE_DESCRIPTION = 'EMIS GP'
    EXCEPT
    SELECT EMPI_ID
    FROM NCL_CODES
    WHERE CODE IN (
        SELECT SNOMED_CODE
        FROM JOINED_LTC_LOOKUP
        WHERE CLUSTER_ID IN ('STATINDEC_COD')
    )
    AND DATETIME >= ADD_MONTHS(CURRENT_DATE(), -60)
    AND SOURCE_DESCRIPTION = 'EMIS GP'
)
-- Final Query to list EMPI_ID and their Source
SELECT 
    COALESCE (EMIS.EMPI_ID, OTHER.EMPI_ID) AS EMPI_ID,
    CASE 
        WHEN EMIS.EMPI_ID IS NOT NULL THEN 'EMIS' 
        ELSE 'OTHER' 
    END AS Source
FROM (
    SELECT EMPI_ID FROM OTHER
    UNION
    SELECT EMPI_ID FROM EMIS
) AS subquery
LEFT JOIN EMIS ON subquery.EMPI_ID = EMIS.EMPI_ID
LEFT JOIN OTHER ON subquery.EMPI_ID = OTHER.EMPI_ID
