--- CREATING CTE FOR EMIS SOURCED
WITH EMIS AS (
select EMPI_ID,
1 as 'EMIS'
FROM (
-- CREATING CTE FOR MOST RECENT QDIABETES SCORE
WITH QDIAB AS (
SELECT EMPI_ID, NORM_NUMERIC_VALUE, SERVICE_LOCAL_DATE_ID AS DATE_OF_LAST_QDIAB, SOURCE_DESCRIPTION FROM PH_F_RESULT c
WHERE RESULT_RAW_CODE IN ('863501000000102')
AND c.SOURCE_DESCRIPTION = 'EMIS GP'
AND (EMPI_ID, SERVICE_LOCAL_DATE_ID) IN (
SELECT EMPI_ID, MAX(SERVICE_LOCAL_DATE_ID) AS SERVICE_LOCAL_DATE_ID
FROM PH_F_RESULT c
GROUP BY EMPI_ID)
),
-- CREATING A) INCLUSION COHORT FOR HBA1C OVER OR EQUAL TO 42 WITHIN LAST 5 YEARS
INCLUSIONA AS (SELECT DISTINCT EMPI_ID, SOURCE_DESCRIPTION
FROM PH_F_RESULT c
JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.RESULT_CODE
AND t.cluster_id IN ('HBA1C')
AND c.NORM_NUMERIC_VALUE>= 42
AND DATE(c.SERVICE_DATE) >=add_months(CURRENT_DATE(), -60)
AND c.SOURCE_DESCRIPTION = 'EMIS GP'
),
-- CREATING B) INCLUSION COHORT FOR MOST RECENT Q DIABETES OVER OR EQUAL TO 5.6
INCLUSIONB AS (SELECT DISTINCT b.EMPI_ID, SOURCE_DESCRIPTION
FROM LTC_LCS_BASE b
INNER JOIN QDIAB USING(EMPI_ID)
WHERE norm_numeric_value>=5.6
AND SOURCE_DESCRIPTION = 'EMIS GP'
),
-- CREATING C) INCLUSION COHORT FOR MOST RECENT Q RISK OVER 20
INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID, SOURCE_DESCRIPTION
FROM LTC_LCS_BASE b
JOIN LTC_QRISK q USING(EMPI_ID)
WHERE norm_numeric_value>20
AND SOURCE_DESCRIPTION = 'EMIS GP'
),
-- CREATING D) INCLUSION COHORT FOR HISTORY OF GESTATIONAL DIABETES
INCLUSIOND AS (SELECT DISTINCT b.EMPI_ID, C.SOURCE_DESCRIPTION
FROM LTC_LCS_BASE b
JOIN PH_F_CONDITION c USING(EMPI_ID)
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
WHERE c.EMPI_ID = b.EMPI_ID
AND t.cluster_id IN ('GESTDIAB_COD')
AND c.SOURCE_DESCRIPTION = 'EMIS GP'
)
-- COMBINING ALL INCLUSION CRITERIA
SELECT DISTINCT * FROM
(SELECT EMPI_ID, SOURCE_DESCRIPTION FROM INCLUSIONA
UNION 
SELECT EMPI_ID, SOURCE_DESCRIPTION FROM INCLUSIONB
UNION 
SELECT EMPI_ID, SOURCE_DESCRIPTION FROM INCLUSIONC
UNION 
SELECT EMPI_ID, SOURCE_DESCRIPTION FROM INCLUSIOND) FINAL

-- REMOVING PATIENTS ON REGISTERS
WHERE NOT EXISTS (
  SELECT 1
  FROM POPHEALTH_QOF_LTCS_LIST l
  WHERE l.EMPI_ID = FINAL.EMPI_ID
  AND l.LTC_NAME IN (
    'Atrial Fibrillation',
    'Asthma',
    'Chronic Kidney Disease',
    'COPD',
    'Coronary Heart Disease',
    'Diabetes',
    'Stroke and TIA',
    'Peripheral Arterial Disease',
    'Heart Failure',
    'Hypertension')
)
-- REMOVING PATIENTS WITH CONDITIONS
AND NOT EXISTS (
  SELECT 1
  FROM PH_F_CONDITION c
  JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE c.EMPI_ID = FINAL.EMPI_ID
  AND t.cluster_id IN ('NDH_COD','PRD_COD')
  AND c.SOURCE_DESCRIPTION = 'EMIS GP'
)
-- REMOVING PATIENTS WITH NHS HEALTH CHECK COMPLETED IN THE LAST 2 YEARS
AND NOT EXISTS (
  SELECT 1
  FROM PH_F_CONDITION c
  JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE c.EMPI_ID = FINAL.EMPI_ID
  AND t.cluster_id = 'HEALTH_CHECK_COMP'
  AND DATE(c.EFFECTIVE_DATE_ID) >=add_months(CURRENT_DATE(), -24)
  AND c.SOURCE_DESCRIPTION = 'EMIS GP'
)) a ) ,


--- CREATING CTE FOR ALL SOURCED
OTHER AS(
SELECT EMPI_ID,
1 as 'OTHER'
FROM (
-- CREATING CTE FOR MOST RECENT QDIABETES SCORE
WITH QDIAB AS (
SELECT EMPI_ID, NORM_NUMERIC_VALUE, SERVICE_LOCAL_DATE_ID AS DATE_OF_LAST_QDIAB FROM PH_F_RESULT c
WHERE RESULT_RAW_CODE IN ('863501000000102')
AND (EMPI_ID, SERVICE_LOCAL_DATE_ID) IN (
SELECT EMPI_ID, MAX(SERVICE_LOCAL_DATE_ID) AS SERVICE_LOCAL_DATE_ID
FROM PH_F_RESULT c
GROUP BY EMPI_ID)
),
-- CREATING A) INCLUSION COHORT FOR HBA1C OVER OR EQUAL TO 42 WITHIN LAST 5 YEARS
INCLUSIONA AS (SELECT DISTINCT EMPI_ID
FROM PH_F_RESULT c
JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.RESULT_CODE
AND t.cluster_id IN ('HBA1C')
AND c.NORM_NUMERIC_VALUE>= 42
AND DATE(c.SERVICE_DATE) >=add_months(CURRENT_DATE(), -60)
),
-- CREATING B) INCLUSION COHORT FOR MOST RECENT Q DIABETES OVER OR EQUAL TO 5.6
INCLUSIONB AS (SELECT DISTINCT b.EMPI_ID
FROM LTC_LCS_BASE b
INNER JOIN QDIAB USING(EMPI_ID)
WHERE norm_numeric_value>=5.6
),
-- CREATING C) INCLUSION COHORT FOR MOST RECENT Q RISK OVER 20
INCLUSIONC AS (SELECT DISTINCT b.EMPI_ID
FROM LTC_LCS_BASE b
JOIN LTC_QRISK q USING(EMPI_ID)
WHERE norm_numeric_value>20
),
-- CREATING D) INCLUSION COHORT FOR HISTORY OF GESTATIONAL DIABETES
INCLUSIOND AS (SELECT DISTINCT b.EMPI_ID
FROM LTC_LCS_BASE b
JOIN PH_F_CONDITION c USING(EMPI_ID)
JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
WHERE c.EMPI_ID = b.EMPI_ID
AND t.cluster_id IN ('GESTDIAB_COD')
)
-- COMBINING ALL INCLUSION CRITERIA
SELECT DISTINCT * FROM
(SELECT EMPI_ID FROM INCLUSIONA
UNION 
SELECT EMPI_ID FROM INCLUSIONB
UNION 
SELECT EMPI_ID FROM INCLUSIONC
UNION 
SELECT EMPI_ID FROM INCLUSIOND) FINAL

-- REMOVING PATIENTS ON REGISTERS
WHERE NOT EXISTS (
  SELECT 1
  FROM POPHEALTH_QOF_LTCS_LIST l
  WHERE l.EMPI_ID = FINAL.EMPI_ID
  AND l.LTC_NAME IN (
    'Atrial Fibrillation',
    'Asthma',
    'Chronic Kidney Disease',
    'COPD',
    'Coronary Heart Disease',
    'Diabetes',
    'Stroke and TIA',
    'Peripheral Arterial Disease',
    'Heart Failure',
    'Hypertension')
)
-- REMOVING PATIENTS WITH CONDITIONS
AND NOT EXISTS (
  SELECT 1
  FROM PH_F_CONDITION c
  JOIN LTC_LCS_LOOKUPTABLE t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE c.EMPI_ID = FINAL.EMPI_ID
  AND t.cluster_id IN ('NDH_COD','PRD_COD')
)
-- REMOVING PATIENTS WITH NHS HEALTH CHECK COMPLETED IN THE LAST 2 YEARS
AND NOT EXISTS (
  SELECT 1
  FROM PH_F_CONDITION c
  JOIN JOINED_LTC_LOOKUP t ON t.SNOMED_CODE = c.CONDITION_CODE
  WHERE c.EMPI_ID = FINAL.EMPI_ID
  AND t.cluster_id = 'HEALTH_CHECK_COMP'
  AND DATE(c.EFFECTIVE_DATE_ID) >=add_months(CURRENT_DATE(), -24)
)) b )

SELECT 
COALESCE(e.empi_id, o.empi_id) as empi_id,
e.EMIS,
o.OTHER
FROM EMIS e
FULL JOIN OTHER o USING (empi_id)