WITH STATINS_NOT_HIGH_DOSE_COMBINED AS (
    SELECT 
        EMPI_ID,
        CASE 
            WHEN SOURCE_DESCRIPTION = 'EMIS GP' THEN 'EMIS' 
            ELSE 'OTHER' 
        END AS Source
    FROM CERNER_MEDICATION_JOINED_TABLE
    WHERE (DRUG_CODE IN (
        SELECT SNOMED_CODE
        FROM JOINED_LTC_LOOKUP
        WHERE CLUSTER_ID = 'STATINS_EXCL_HIGH_DOSE')--'STATIN_CODES_CVD_65')
        or drug_code in (  -------------remove once clusters updated
        '409108001',
				'39832311000001101',
				'39832611000001106',
				'39832411000001108',
				'40917311000001100',
				'39832511000001107',
				'9747511000001107 '
        				)
        	)
    AND STATUS_DISPLAY = 'Active'
    AND (STOP_DT_TM > CURRENT_DATE() or STOP_DT_TM is null)
)

SELECT 
    COMBINED.EMPI_ID,
    COMBINED.Source
FROM STATINS_NOT_HIGH_DOSE_COMBINED AS COMBINED
INNER JOIN ICB_CF_CVD_63_BASE AS BASE ON BASE.EMPI_ID = COMBINED.EMPI_ID

EXCEPT

SELECT EMPI_ID, 'PLACEHOLDER' as Source
FROM NCL_CODES
WHERE CODE IN (
    SELECT SNOMED_CODE
    FROM JOINED_LTC_LOOKUP
    WHERE CLUSTER_ID IN ('STATIN_ALLERGY_ADVERSE_REACTION', 'STATIN_NOT_INDICATED')
)
