WITH CARDIAC_RISK_SCORES_EMIS AS (
    SELECT 
        sub.EMPI_ID
    FROM (
        SELECT 
            EMPI_ID,
            NORM_NUMERIC_VALUE,
            ROW_NUMBER() OVER (PARTITION BY EMPI_ID ORDER BY SERVICE_DATE DESC, NORM_NUMERIC_VALUE DESC) as rn
        FROM PH_F_RESULT
        WHERE RESULT_CODE IN ('752451000000100','809311000000105','718087004','1085871000000105','450759008','763244005')
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
        AND SOURCE_DESCRIPTION = 'EMIS GP' AND NORM_NUMERIC_VALUE >0
        AND SERVICE_DATE < NOW()
    ) AS sub
    INNER JOIN ICB_CF_CVD_61_BASE AS BASE ON BASE.EMPI_ID = sub.EMPI_ID AND BASE.SOURCE = 'EMIS'
    WHERE sub.rn = 1 AND sub.NORM_NUMERIC_VALUE BETWEEN 15 AND 19.99
),

CARDIAC_RISK_SCORES_OTHER AS (
    SELECT 
        sub.EMPI_ID
    FROM (
        SELECT 
            EMPI_ID,
            NORM_NUMERIC_VALUE,
            ROW_NUMBER() OVER (PARTITION BY EMPI_ID ORDER BY SERVICE_DATE DESC, NORM_NUMERIC_VALUE DESC) as rn
        FROM PH_F_RESULT
        WHERE RESULT_CODE IN ('752451000000100','809311000000105','718087004','1085871000000105','450759008','763244005')
            -- SELECT SNOMED_CODE
            --FROM JOINED_LTC_LOOKUP
            --WHERE CLUSTER_ID = 'CARDIAC_RISK_SCORE')
            AND NORM_NUMERIC_VALUE >0
        AND SERVICE_DATE < NOW()
    ) AS sub
    INNER JOIN ICB_CF_CVD_61_BASE AS BASE ON BASE.EMPI_ID = sub.EMPI_ID
    WHERE sub.rn = 1 AND sub.NORM_NUMERIC_VALUE BETWEEN 15 AND 19.99
)

SELECT 
    COALESCE (EMIS.EMPI_ID, OTHER.EMPI_ID) AS EMPI_ID,
    CASE 
        WHEN EMIS.EMPI_ID IS NOT NULL THEN 'EMIS' 
        ELSE 'OTHER' 
    END AS Source
FROM (
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_EMIS
    UNION
    SELECT EMPI_ID FROM CARDIAC_RISK_SCORES_OTHER
) AS subquery
LEFT JOIN CARDIAC_RISK_SCORES_EMIS AS EMIS ON subquery.EMPI_ID = EMIS.EMPI_ID
LEFT JOIN CARDIAC_RISK_SCORES_OTHER AS OTHER ON subquery.EMPI_ID = OTHER.EMPI_ID