#!/usr/bin/env python3
"""
Script to fix YAML formatting issues and remove "Generated by dbt" lines from descriptions.

This script:
1. Fixes extra spaces between lines in YAML descriptions
2. Removes the "🤖 Generated by dbt..." lines from descriptions 
3. Ensures proper YAML formatting
"""

import yaml
import re
from pathlib import Path
from typing import Dict, List

def clean_description(description: str) -> str:
    """
    Clean a description by removing extra spaces and Generated by dbt lines.
    
    Args:
        description (str): Original description
        
    Returns:
        str: Cleaned description
    """
    if not description:
        return description
    
    # Remove the "Generated by dbt" line and variations
    lines = description.split('\n')
    cleaned_lines = []
    
    for line in lines:
        # Skip lines that contain the "Generated by dbt" text
        if '🤖 Generated by dbt' in line or 'Generated by dbt' in line:
            continue
        if 'for model definitions and documentation, see https://github.com/' in line:
            continue
        cleaned_lines.append(line)
    
    # Join lines back together
    cleaned_description = '\n'.join(cleaned_lines)
    
    # Remove excessive blank lines (more than 2 consecutive newlines)
    cleaned_description = re.sub(r'\n{3,}', '\n\n', cleaned_description)
    
    # Remove trailing whitespace from each line
    lines = cleaned_description.split('\n')
    lines = [line.rstrip() for line in lines]
    cleaned_description = '\n'.join(lines)
    
    # Remove leading/trailing newlines
    cleaned_description = cleaned_description.strip()
    
    return cleaned_description

def process_yaml_file(file_path: Path) -> bool:
    """
    Process a single YAML file to fix formatting issues.
    
    Args:
        file_path (Path): Path to the YAML file
        
    Returns:
        bool: True if file was modified, False otherwise
    """
    try:
        # Read the file
        with open(file_path, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)
        
        if not data:
            return False
        
        modified = False
        
        # Process models section
        models = data.get('models', [])
        for model in models:
            if 'description' in model:
                original_desc = model['description']
                cleaned_desc = clean_description(original_desc)
                
                if original_desc != cleaned_desc:
                    model['description'] = cleaned_desc
                    modified = True
                    print(f"    Cleaned description for model: {model.get('name', 'unnamed')}")
            
            # Process column descriptions as well
            columns = model.get('columns', [])
            for column in columns:
                if 'description' in column:
                    original_desc = column['description']
                    cleaned_desc = clean_description(original_desc)
                    
                    if original_desc != cleaned_desc:
                        column['description'] = cleaned_desc
                        modified = True
        
        # Save file if modified
        if modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                yaml.dump(data, f, 
                         default_flow_style=False, 
                         sort_keys=False,
                         allow_unicode=True, 
                         width=1000,
                         indent=2,
                         default_style=None)
        
        return modified
    
    except Exception as e:
        print(f"    Error processing {file_path}: {e}")
        return False

def find_yaml_files(base_path: Path) -> List[Path]:
    """
    Find all YAML schema files to process.
    
    Args:
        base_path (Path): Base path to search
        
    Returns:
        List[Path]: List of YAML files to process
    """
    yaml_files = []
    
    # Search in models directory for .yml files
    models_path = base_path / 'models'
    if models_path.exists():
        yaml_files.extend(models_path.rglob('*.yml'))
    
    return sorted(yaml_files)

def main():
    """Main function to fix YAML formatting issues."""
    print("🔄 Starting YAML formatting fix...")
    
    # Get project root directory
    project_root = Path('/mnt/c/Projects/snowflake-hei-migration-dbt')
    
    print(f"📁 Project root: {project_root}")
    
    # Find all YAML files
    yaml_files = find_yaml_files(project_root)
    print(f"🔍 Found {len(yaml_files)} YAML files to process")
    
    # Track statistics
    processed_count = 0
    modified_count = 0
    error_count = 0
    
    for yaml_path in yaml_files:
        relative_path = yaml_path.relative_to(project_root)
        
        # Skip certain files that might not need processing
        if any(skip in str(relative_path) for skip in ['sources.yml']):
            continue
        
        print(f"\n📄 Processing: {relative_path}")
        
        # Process the file
        try:
            modified = process_yaml_file(yaml_path)
            processed_count += 1
            
            if modified:
                modified_count += 1
                print(f"  ✅ Fixed formatting issues")
            else:
                print(f"  ℹ️  No changes needed")
        except Exception as e:
            print(f"  ❌ Error: {e}")
            error_count += 1
    
    # Print summary
    print(f"\n📊 YAML Formatting Fix Summary:")
    print(f"   Processed: {processed_count} files")
    print(f"   Modified:  {modified_count} files")
    print(f"   Errors:    {error_count} files")
    
    if modified_count > 0:
        print(f"\n✨ Successfully fixed formatting in {modified_count} YAML files!")
        print("💡 Next step: Test the macro approach with updated schema files")
    else:
        print("\n🎯 No formatting issues found or all were already fixed.")

if __name__ == "__main__":
    main()