-- Script to update cluster IDs in LTC_LCS_CODES to use consistent SCREAMING_SNAKE_CASE naming
-- This uses a mapping table approach to ensure consistency and traceability

CREATE OR REPLACE TEMPORARY TABLE DATA_LAB_NCL_TRAINING_TEMP.CODESETS.CLUSTER_ID_MAPPING (
    OLD_CLUSTER_ID VARCHAR,
    NEW_CLUSTER_ID VARCHAR,
    REASONING VARCHAR
) AS
SELECT * FROM VALUES
    -- Medication/Drug related
    ('ORANTICOAG_2.8.2', 'ORAL_ANTICOAGULANT_2_8_2', 'Standardize anticoagulant naming and replace dots with underscores'),
    ('DRUGS_USED_IN_AF', 'AF_MEDICATIONS', 'More concise and consistent with other medication naming'),
    ('CARDIAC GLYCOSIDES', 'CARDIAC_GLYCOSIDES', 'Replace space with underscore'),
    ('LTC_ARBS', 'ARB_MEDICATIONS', 'Remove LTC prefix and standardize medication naming'),
    ('LTC_SGLT2', 'SGLT2_MEDICATIONS', 'Remove LTC prefix and standardize medication naming'),
    ('LTC_CARDIAC_GLYCOSIDES', 'CARDIAC_GLYCOSIDES', 'Remove redundant LTC prefix'),
    ('Prednisolone', 'PREDNISOLONE_MEDICATIONS', 'Standardize medication naming'),
    ('Montelukast', 'MONTELUKAST_MEDICATIONS', 'Standardize medication naming'),
    ('lithium', 'LITHIUM_MEDICATIONS', 'Standardize medication naming'),
    ('Tacrolimus_Drug', 'TACROLIMUS_MEDICATIONS', 'Standardize medication naming'),
    ('sulfasalazine_drug', 'SULFASALAZINE_MEDICATIONS', 'Standardize medication naming'),
    ('Calcineurin', 'CALCINEURIN_MEDICATIONS', 'Standardize medication naming'),
    ('PROTAMINE_DRUGS', 'PROTAMINE_MEDICATIONS', 'Standardize medication naming'),
    ('HF_R2_DRUGS', 'HF_R2_MEDICATIONS', 'Standardize medication naming'),
    ('HF_R3_DRUGS', 'HF_R3_MEDICATIONS', 'Standardize medication naming'),
    ('HF_R4_DRUGS', 'HF_R4_MEDICATIONS', 'Standardize medication naming'),
    ('HF_MEDICATIONS', 'HF_MEDICATIONS', 'Already correct format'),
    ('DIGOXIN', 'DIGOXIN_MEDICATIONS', 'Standardize medication naming'),
    ('CORTICOST_COD', 'CORTICOSTEROID_MEDICATIONS', 'Standardize medication naming'),
    ('INHALER_DRY', 'DRY_POWDER_INHALER', 'More descriptive and consistent naming'),
    ('SALBUTAMOL_COD', 'SALBUTAMOL_MEDICATIONS', 'Standardize medication naming'),
    ('NITRIC_COD', 'NITRIC_OXIDE_MEDICATIONS', 'Standardize medication naming'),
    ('NITROUS_OX', 'NITROUS_OXIDE_MEDICATIONS', 'Standardize medication naming'),

    -- Condition/Diagnosis related
    ('Diabetes_type_2', 'TYPE_2_DIABETES', 'Standardize diabetes naming'),
    ('Pre-diabetes', 'PREDIABETES', 'Remove hyphen and standardize'),
    ('Sus_asthma', 'SUSPECTED_ASTHMA', 'More descriptive and consistent'),
    ('Viral_wheeze', 'VIRAL_WHEEZE', 'Standardize to uppercase'),
    ('EMIS_VIRAL_WHEEZE', 'VIRAL_WHEEZE', 'Remove EMIS prefix'),
    ('EMIS_AST_DIAG', 'ASTHMA_DIAGNOSIS', 'Remove EMIS prefix and standardize'),
    ('EMIS_AST_DRUG', 'ASTHMA_MEDICATIONS', 'Remove EMIS prefix and standardize'),
    ('LCS_DM_DIAGNOSIS', 'DIABETES_DIAGNOSIS', 'Remove LCS prefix'),
    ('CKD_STAT_DIAG', 'CKD_DIAGNOSIS', 'Remove redundant STAT'),
    ('CKD_STAT_THER', 'CKD_TREATMENT', 'Remove redundant STAT and standardize THER'),
    ('AST_DIAG', 'ASTHMA_DIAGNOSIS', 'Standardize asthma naming'),
    ('AST_DRUG', 'ASTHMA_MEDICATIONS', 'Standardize asthma naming'),
    ('AST_PREDNIL', 'ASTHMA_PREDNISOLONE', 'Standardize asthma naming'),
    ('ASTHMA_ATTACK', 'ASTHMA_EXACERBATION', 'More clinical terminology'),
    ('ASTHMA_MONITOR', 'ASTHMA_MONITORING', 'Standardize monitoring naming'),
    ('ASTHMA_MONITOR1', 'ASTHMA_MONITORING_1', 'Standardize monitoring naming'),
    ('ASTHMA_REV_COD', 'ASTHMA_REVIEW', 'Remove redundant COD'),
    ('ASTHMA_MONITOR', 'ASTHMA_MONITORING', 'Standardize monitoring naming'),
    ('CKD_AKI', 'CKD_ACUTE_KIDNEY_INJURY', 'Spell out AKI'),
    ('CKD_BPH_GOUT', 'CKD_BPH_GOUT', 'Already correct format'),
    ('CKD_MON', 'CKD_MONITORING', 'Spell out MON'),
    ('CKD_FLOZIN', 'CKD_SGLT2_MEDICATIONS', 'More descriptive naming'),
    ('PE', 'PULMONARY_EMBOLISM', 'Spell out PE'),
    ('NAFLD', 'NON_ALCOHOLIC_FATTY_LIVER_DISEASE', 'Spell out NAFLD'),
    ('NAFLD_COD', 'NON_ALCOHOLIC_FATTY_LIVER_DISEASE', 'Remove redundant COD'),
    ('FIBROSIS_COD', 'LIVER_FIBROSIS', 'More descriptive and remove redundant COD'),
    ('LIV_FIBROSIS', 'LIVER_FIBROSIS', 'Standardize liver naming'),
    ('HF_EXCLUDED', 'HEART_FAILURE_EXCLUSIONS', 'More descriptive'),
    ('HF_EXCLUSIONS', 'HEART_FAILURE_EXCLUSIONS', 'More descriptive'),
    ('HF_BASE_DIURETIC', 'HEART_FAILURE_DIURETIC', 'Standardize heart failure naming'),
    ('HF_R5_DIFF_BREATH', 'HEART_FAILURE_R5_DYSPNOEA', 'Standardize heart failure naming'),
    ('HF_R7R9_PROBNP100', 'HEART_FAILURE_R7R9_PROBNP_100', 'Standardize heart failure naming'),
    ('HF_R8A_SUBSET_PROBNP', 'HEART_FAILURE_R8A_PROBNP_SUBSET', 'Standardize heart failure naming'),
    ('HF_R5_CARDIOM', 'HEART_FAILURE_R5_CARDIOMYOPATHY', 'Spell out CARDIOM'),
    ('HF_R6_LV', 'HEART_FAILURE_R6_LEFT_VENTRICULAR', 'Spell out LV'),
    ('HF_R9_ECHO', 'HEART_FAILURE_R9_ECHOCARDIOGRAM', 'Spell out ECHO'),
    ('LTC_CARDIAC_ASSESSMENTS', 'CARDIAC_ASSESSMENTS', 'Remove LTC prefix'),
    ('LTC_CARDIOMYOPATHY', 'CARDIOMYOPATHY', 'Remove LTC prefix'),
    ('LTC_BREATHLESS', 'BREATHLESSNESS', 'Remove LTC prefix'),
    ('LTC_PROBNP', 'PROBNP_TESTING', 'Remove LTC prefix and add context'),
    ('LTC_DERM_CONDITIONS', 'DERMATOLOGICAL_CONDITIONS', 'Remove LTC prefix and standardize'),
    ('LTC_PERIPHERAL_VASCULAR_ISSUES', 'PERIPHERAL_VASCULAR_DISEASE', 'Remove LTC prefix and standardize'),
    ('LTC_ARTERY_DISORDERS', 'ARTERIAL_DISORDERS', 'Remove LTC prefix and standardize'),
    ('LTC_CEREBROVASCULAR_EVENTS', 'CEREBROVASCULAR_EVENTS', 'Remove LTC prefix'),
    ('LTC_TRANSIENT_ISCHEMIC_EVENTS', 'TRANSIENT_ISCHEMIC_ATTACKS', 'Remove LTC prefix and standardize'),
    ('LTC_CKD_STAGES', 'CKD_STAGES', 'Remove LTC prefix'),
    ('LTC_STAT_COD_CVD', 'CVD_STATIN_MEDICATIONS', 'Remove LTC prefix and standardize'),
    ('LTC_PULSE_RATE', 'PULSE_RATE', 'Remove LTC prefix'),
    ('LTC_PULSE_RHYTHM', 'PULSE_RHYTHM', 'Remove LTC prefix'),
    ('LTC_GFR', 'GFR_TESTING', 'Remove LTC prefix and add context'),

    -- Measurement/Observation related
    ('blood_gluc_lev', 'BLOOD_GLUCOSE_LEVEL', 'Standardize glucose naming'),
    ('diastolic_BP', 'DIASTOLIC_BLOOD_PRESSURE', 'Standardize blood pressure naming'),
    ('systolic_BP', 'SYSTOLIC_BLOOD_PRESSURE', 'Standardize blood pressure naming'),
    ('BP_AMB_HOM_DIA', 'AMBULATORY_HOME_DIASTOLIC_BP', 'More descriptive'),
    ('BP_AMB_HOM_SYS', 'AMBULATORY_HOME_SYSTOLIC_BP', 'More descriptive'),
    ('DIASTOLIC_BP', 'DIASTOLIC_BLOOD_PRESSURE', 'Standardize blood pressure naming'),
    ('SYSTOLIC_BP', 'SYSTOLIC_BLOOD_PRESSURE', 'Standardize blood pressure naming'),
    ('HBA1C', 'HBA1C_LEVEL', 'Standardize HBA1C naming'),
    ('HbA1c', 'HBA1C_LEVEL', 'Standardize HBA1C naming'),
    ('HBA1C_LEVEL', 'HBA1C_LEVEL', 'Already correct format'),
    ('FRUCTOSAMINE', 'FRUCTOSAMINE_LEVEL', 'Add context'),
    ('CHOL_LEVEL', 'CHOLESTEROL_LEVEL', 'Spell out CHOL'),
    ('NON_HDL_CHOL', 'NON_HDL_CHOLESTEROL', 'Spell out CHOL'),
    ('EGFR_COD_LCS', 'EGFR_TESTING', 'Remove redundant COD and LCS'),
    ('UACR_COD', 'UACR_TESTING', 'Remove redundant COD'),
    ('UACR_COD_LCS', 'UACR_TESTING', 'Remove redundant COD and LCS'),
    ('BMI_CODES', 'BMI_MEASUREMENT', 'More descriptive'),
    ('QRISK2', 'QRISK2_ASSESSMENT', 'Add context'),
    ('QRISK2_10y', 'QRISK2_10YEAR', 'Standardize year naming'),
    ('QDiabetes_risk', 'QDIABETES_RISK', 'Standardize to uppercase'),
    ('CARDIAC_RISK_SCORE', 'CARDIAC_RISK_ASSESSMENT', 'Standardize assessment naming'),
    ('NYHAC_HF', 'NYHA_HEART_FAILURE_CLASSIFICATION', 'Spell out NYHAC and HF'),
    ('MRC_BREATH', 'MRC_BREATHLESSNESS_SCALE', 'Spell out BREATH'),
    ('SPIROMETRY_COD', 'SPIROMETRY_TESTING', 'Remove redundant COD'),
    ('PULRHBATT_COD_32', 'PULSE_RHYTHM_BATTERY_32', 'Spell out PULRHBATT'),
    ('PULMONARY_EX', 'PULMONARY_EXERCISE_TESTING', 'Spell out EX'),
    ('HTN_RES', 'HYPERTENSION_RESISTANT', 'Spell out HTN and RES'),
    ('HTN_WHITE_COAT', 'HYPERTENSION_WHITE_COAT', 'Spell out HTN'),
    ('HTN_COD', 'HYPERTENSION', 'Remove redundant COD and spell out HTN'),
    ('HTN_SYSTOLIC_1', 'HYPERTENSION_SYSTOLIC_1', 'Spell out HTN'),
    ('HTN_SYSTOLIC_2', 'HYPERTENSION_SYSTOLIC_2', 'Spell out HTN'),
    ('HTN_DIASTOLIC_1', 'HYPERTENSION_DIASTOLIC_1', 'Spell out HTN'),
    ('HTN_DIASTOLIC_2', 'HYPERTENSION_DIASTOLIC_2', 'Spell out HTN'),
    ('HTN_AMBULATORY_DIASTOLIC', 'HYPERTENSION_AMBULATORY_DIASTOLIC', 'Spell out HTN'),
    ('HTN_AMBULATORY_SYSTOLIC', 'HYPERTENSION_AMBULATORY_SYSTOLIC', 'Spell out HTN'),
    ('HTN_CEREBRAL', 'HYPERTENSION_CEREBRAL', 'Spell out HTN'),
    ('HTN_CLAUDICATION', 'HYPERTENSION_CLAUDICATION', 'Spell out HTN'),
    ('HTN_EGFR', 'HYPERTENSION_EGFR', 'Spell out HTN'),
    ('HTN_DIABETES', 'HYPERTENSION_DIABETES', 'Spell out HTN'),
    ('HTN_BMI', 'HYPERTENSION_BMI', 'Spell out HTN'),
    ('HTN_BSA_COD', 'HYPERTENSION_BSA', 'Spell out HTN and remove redundant COD'),
    ('HTN_MYOCARDIAL', 'HYPERTENSION_MYOCARDIAL', 'Spell out HTN'),
    ('HTN_CKD', 'HYPERTENSION_CKD', 'Spell out HTN'),

    -- Ethnicity related
    ('WHITE_BRITISH', 'ETHNICITY_WHITE_BRITISH', 'Add context'),
    ('BAME_ETHNICITY', 'ETHNICITY_BAME', 'Standardize ethnicity naming'),
    ('DM_EXCL_ETHNICITY', 'DIABETES_EXCLUDED_ETHNICITY', 'Spell out DM'),

    -- Other
    ('NDPP_comp', 'NDPP_COMPLETED', 'Spell out comp'),
    ('NDPP_inv', 'NDPP_INVITED', 'Spell out inv'),
    ('NDPP_not_comp', 'NDPP_NOT_COMPLETED', 'Spell out not_comp'),
    ('NDPP_ref', 'NDPP_REFERRED', 'Spell out ref'),
    ('NDPP_ref_pro', 'NDPP_REFERRAL_PROCESS', 'Spell out ref_pro'),
    ('NDPP_start', 'NDPP_STARTED', 'Add context'),
    ('PCARE_PLAN', 'PERSONALISED_CARE_PLAN', 'Spell out PCARE'),
    ('EXERCISE_ADV', 'EXERCISE_ADVICE', 'Spell out ADV'),
    ('SMOK_HOUSE_COD', 'SMOKING_HOUSING', 'Spell out SMOK and remove redundant COD'),
    ('STAT_COD_LIP', 'STATIN_LIPID_MEDICATIONS', 'Spell out STAT and LIP'),
    ('STAT_COD_LCS_CVD_CF_GPIT_MATCH', 'STATIN_CVD_MEDICATIONS', 'Simplify and standardize'),
    ('STATIN_CODES_CVD_63', 'STATIN_CVD_63_MEDICATIONS', 'Standardize medication naming'),
    ('STATIN_CODES_CVD_64', 'STATIN_CVD_64_MEDICATIONS', 'Standardize medication naming'),
    ('STATIN_CODES_CVD_65', 'STATIN_CVD_65_MEDICATIONS', 'Standardize medication naming'),
    ('STATIN_NOT_INDICATED', 'STATIN_NOT_INDICATED', 'Already correct format'),
    ('STATINS_EXCL_HIGH_DOSE', 'STATIN_EXCLUDED_HIGH_DOSE', 'Standardize medication naming'),
    ('STATIN_ALLERGY_ADVERSE_REACTION', 'STATIN_ALLERGY_ADVERSE_REACTION', 'Already correct format'),
    ('DM_ANREVIEW', 'DIABETES_ANNUAL_REVIEW', 'Spell out DM and ANREVIEW'),
    ('DM_GESTDIAB_AND_PREG_RISK', 'GESTATIONAL_DIABETES_PREGNANCY_RISK', 'Spell out DM and standardize'),
    ('DM_REMISSION', 'DIABETES_REMISSION', 'Spell out DM'),
    ('Hist_gest_diabetes', 'HISTORY_GESTATIONAL_DIABETES', 'Standardize to uppercase and spell out'),
    ('Hematuria', 'HAEMATURIA', 'British English spelling'),
    ('Urine_Blood_Neg', 'URINE_BLOOD_NEGATIVE', 'Spell out Neg'),
    ('AF_FLUTTER', 'ATRIAL_FLUTTER', 'Spell out AF'),
    ('AF61_EXCLUSIONS', 'ATRIAL_FIBRILLATION_61_EXCLUSIONS', 'Spell out AF'),
    ('DVT', 'DEEP_VEIN_THROMBOSIS', 'Spell out DVT'),
    ('DRUGUSE_COD', 'DRUG_USE', 'Remove redundant COD'),
    ('PRED_COD', 'PREDNISOLONE_MEDICATIONS', 'Remove redundant COD and standardize medication naming')
;

-- Update the LTC_LCS_CODES table with the new cluster IDs
UPDATE DATA_LAB_NCL_TRAINING_TEMP.CODESETS.LTC_LCS_CODES t
SET CLUSTER_ID = m.NEW_CLUSTER_ID
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.CLUSTER_ID_MAPPING m
WHERE t.CLUSTER_ID = m.OLD_CLUSTER_ID;

-- Add a comment to the table explaining the naming convention
COMMENT ON TABLE DATA_LAB_NCL_TRAINING_TEMP.CODESETS.LTC_LCS_CODES IS 'Cluster IDs follow SCREAMING_SNAKE_CASE convention. All spaces, dots, and hyphens are replaced with underscores. Common abbreviations are spelled out (e.g., AF → ATRIAL_FIBRILLATION, CKD → CHRONIC_KIDNEY_DISEASE). Medication-related clusters end with _MEDICATIONS, measurement-related clusters end with _LEVEL or _TESTING as appropriate.';

-- Log the changes
SELECT 
    OLD_CLUSTER_ID,
    NEW_CLUSTER_ID,
    REASONING,
    'Updated' as STATUS
FROM DATA_LAB_NCL_TRAINING_TEMP.CODESETS.CLUSTER_ID_MAPPING
ORDER BY OLD_CLUSTER_ID; 