{{
    config(
        materialized='table',
        tags=['dimension', 'person', 'sex'],
        cluster_by=['person_id'],
        post_hook=[
            "COMMENT ON TABLE {{ this }} IS 'Mart: Person Sex Dimension - Sex demographics for population analysis.

Population Scope:
• All persons with patient records
• Derived from gender_concept_id mappings
• Defaults to \"Unknown\" for unmapped or null values

Key Features:
• Standardised sex categories (Male, Female, Unknown)
• Hardcoded concept ID mappings for data consistency
• One row per person with sex classification

🤖 Generated by dbt. This table is managed by dbt - for model definitions and documentation, see https://github.com/ncl-icb-analytics/snowflake-hei-migration'"
        ]
    )
}}

-- Person Sex Dimension Table
-- Derives sex from hardcoded gender_concept_id values

SELECT DISTINCT
    pp.person_id,
    -- Derives sex by mapping specific gender_concept_id values to 'Female' or 'Male'
    -- Any other gender_concept_id or a NULL value results in 'Unknown'
    CASE
        WHEN p.gender_concept_id = '4907ce31-7168-4385-b91d-a7fe171a1c8f' THEN 'Female' -- Hardcoded ID for Female
        WHEN p.gender_concept_id = '3ae10994-efd0-47db-ade4-e440eaf0f973' THEN 'Male'   -- Hardcoded ID for Male
        ELSE 'Unknown' -- Default for NULL or any other gender_concept_id values
    END AS sex
FROM {{ ref('stg_olids_patient') }} AS p
INNER JOIN {{ ref('stg_olids_patient_person') }} AS pp
    ON p.id = pp.patient_id
