CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_SUMMARY (
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    -- Indicator flags
    IN_CKD_62 BOOLEAN, -- Two consecutive UACR readings above 4
    IN_CVD_61 BOOLEAN, -- High QRISK2
    IN_CVD_62 BOOLEAN, -- Moderate QRISK2
    IN_CVD_63 BOOLEAN, -- Statin Review
    IN_CVD_64 BOOLEAN, -- High Dose Statins
    IN_CVD_65 BOOLEAN, -- Moderate Dose Statins
    -- Metadata
    LAST_REFRESH_DATE TIMESTAMP,
    INDICATOR_VERSION VARCHAR
)
COMMENT = 'Summary table for LTC LCS case finding indicators. Shows which indicators each person is included in, focusing on indicator flags rather than detailed dimension data.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH BasePopulation AS (
    -- Get base population
    SELECT DISTINCT
        bp.PERSON_ID,
        bp.SK_PATIENT_ID,
        age.AGE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_BASE_POPULATION bp
    JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_AGE age
        USING (PERSON_ID)
)
-- Final selection
SELECT
    bp.PERSON_ID,
    bp.SK_PATIENT_ID,
    bp.AGE,
    -- Indicator flags
    COALESCE(ckd62.HAS_ELEVATED_UACR, FALSE) AS IN_CKD_62,
    COALESCE(cvd61.HAS_HIGH_QRISK2, FALSE) AS IN_CVD_61,
    COALESCE(cvd62.HAS_MODERATE_QRISK2, FALSE) AS IN_CVD_62,
    COALESCE(cvd63.NEEDS_STATIN_REVIEW, FALSE) AS IN_CVD_63,
    COALESCE(cvd64.NEEDS_HIGH_DOSE_STATIN, FALSE) AS IN_CVD_64,
    COALESCE(cvd65.NEEDS_MODERATE_DOSE_STATIN, FALSE) AS IN_CVD_65,
    -- Metadata
    CURRENT_TIMESTAMP() AS LAST_REFRESH_DATE,
    '1.0' AS INDICATOR_VERSION
FROM BasePopulation bp
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_62 ckd62
    ON bp.PERSON_ID = ckd62.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_61 cvd61
    ON bp.PERSON_ID = cvd61.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_62 cvd62
    ON bp.PERSON_ID = cvd62.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_63 cvd63
    ON bp.PERSON_ID = cvd63.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_64 cvd64
    ON bp.PERSON_ID = cvd64.PERSON_ID
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_65 cvd65
    ON bp.PERSON_ID = cvd65.PERSON_ID; 