CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_SUMMARY (
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    -- AF indicators
    IN_AF_61 BOOLEAN, -- On AF-related medications (digoxin, anticoagulants, etc.)
    IN_AF_62 BOOLEAN, -- Missing pulse check
    -- CKD indicators
    IN_CKD_61 BOOLEAN, -- Two consecutive eGFR readings below 60
    IN_CKD_62 BOOLEAN, -- Two consecutive UACR readings above 4
    IN_CKD_63 BOOLEAN, -- Latest UACR reading above 70
    IN_CKD_64 BOOLEAN, -- Specific conditions (AKI, BPH/Gout, Lithium, Microhaematuria)
    -- CVD indicators
    IN_CVD_61 BOOLEAN, -- High QRISK2 (≥20%)
    IN_CVD_62 BOOLEAN, -- Moderate QRISK2 (15-19.99%)
    IN_CVD_63 BOOLEAN, -- Needs statin review
    IN_CVD_64 BOOLEAN, -- Needs high-dose statins
    IN_CVD_65 BOOLEAN, -- Needs moderate-dose statins
    IN_CVD_66 BOOLEAN, -- Needs statin review (75-83 years)
    -- CYP Asthma indicator
    IN_CYP_AST_61 BOOLEAN, -- CYP asthma review needed
    -- Diabetes indicators
    IN_DM_61 BOOLEAN, -- At risk of diabetes (HbA1c, QDiabetes, QRisk, or gestational diabetes history)
    IN_DM_62 BOOLEAN, -- Gestational diabetes and pregnancy risk, no recent HbA1c
    IN_DM_63 BOOLEAN, -- HbA1c between 46-48, no recent HbA1c
    IN_DM_64 BOOLEAN, -- High BMI (≥32.5 BAME, ≥35 non-BAME), no recent HbA1c
    IN_DM_65 BOOLEAN, -- Moderate-high BMI (27.5-32.5 BAME, 30-35 non-BAME), no recent HbA1c
    IN_DM_66 BOOLEAN, -- HbA1c between 42-46 in last 12 months
    -- Metadata
    LAST_REFRESH_DATE TIMESTAMP,
    INDICATOR_VERSION VARCHAR
)
COMMENT = 'Summary table for LTC LCS case finding indicators. Shows which indicators each person is included in, focusing on indicator flags rather than detailed dimension data.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH BasePopulation AS (
    -- Get base population
    SELECT DISTINCT
        bp.PERSON_ID,
        bp.SK_PATIENT_ID,
        age.AGE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_BASE_POPULATION bp
    JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_AGE age
        USING (PERSON_ID)
)
-- Final selection
SELECT
    bp.PERSON_ID,
    bp.SK_PATIENT_ID,
    bp.AGE,
    -- AF indicators
    af61.PERSON_ID IS NOT NULL AS IN_AF_61,
    af62.PERSON_ID IS NOT NULL AS IN_AF_62,
    -- CKD indicators
    ckd61.PERSON_ID IS NOT NULL AS IN_CKD_61,
    ckd62.PERSON_ID IS NOT NULL AS IN_CKD_62,
    ckd63.PERSON_ID IS NOT NULL AS IN_CKD_63,
    ckd64.PERSON_ID IS NOT NULL AS IN_CKD_64,
    -- CVD indicators
    cvd61.PERSON_ID IS NOT NULL AS IN_CVD_61,
    cvd62.PERSON_ID IS NOT NULL AS IN_CVD_62,
    cvd63.PERSON_ID IS NOT NULL AS IN_CVD_63,
    cvd64.PERSON_ID IS NOT NULL AS IN_CVD_64,
    cvd65.PERSON_ID IS NOT NULL AS IN_CVD_65,
    cvd66.PERSON_ID IS NOT NULL AS IN_CVD_66,
    -- CYP Asthma indicator
    cypast61.PERSON_ID IS NOT NULL AS IN_CYP_AST_61,
    -- Diabetes indicators
    dm61.PERSON_ID IS NOT NULL AS IN_DM_61,
    dm62.PERSON_ID IS NOT NULL AS IN_DM_62,
    dm63.PERSON_ID IS NOT NULL AS IN_DM_63,
    dm64.PERSON_ID IS NOT NULL AS IN_DM_64,
    dm65.PERSON_ID IS NOT NULL AS IN_DM_65,
    dm66.PERSON_ID IS NOT NULL AS IN_DM_66,
    -- Metadata
    CURRENT_TIMESTAMP() AS LAST_REFRESH_DATE,
    '1.0' AS INDICATOR_VERSION
FROM BasePopulation bp
-- AF indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_AF_61 af61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_AF_62 af62
    USING (PERSON_ID)
-- CKD indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_61 ckd61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_62 ckd62
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_63 ckd63
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_64 ckd64
    USING (PERSON_ID)
-- CVD indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_61 cvd61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_62 cvd62
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_63 cvd63
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_64 cvd64
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_65 cvd65
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_66 cvd66
    USING (PERSON_ID)
-- CYP Asthma indicator
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CYP_AST_61 cypast61
    USING (PERSON_ID)
-- Diabetes indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_61 dm61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_62 dm62
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_63 dm63
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_64 dm64
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_65 dm65
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_DM_66 dm66
    USING (PERSON_ID); 