CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_VALPROATE_ARAF (
    PERSON_ID VARCHAR COMMENT 'Unique identifier for the person',
    SK_PATIENT_ID VARCHAR COMMENT 'Surrogate key for the patient',
    HAS_ARAF_EVENT BOOLEAN COMMENT 'Always TRUE for persons in this table, indicating at least one ARAF-related event meeting criteria',
    EARLIEST_ARAF_EVENT_DATE DATE COMMENT 'Earliest date of any ARAF-related event for the person, after lookback',
    LATEST_ARAF_EVENT_DATE DATE COMMENT 'Latest date of any ARAF-related event for the person, after lookback',
    LATEST_SPECIFIC_ARAF_FORM_DATE DATE COMMENT 'Latest date of a specific ARAF form (codes 1366401000000107 or 2078951000000106) meeting its lookback',
    HAS_SPECIFIC_ARAF_FORM_MEETING_LOOKBACK BOOLEAN COMMENT 'TRUE if a specific ARAF form code meeting its lookback is recorded',
    ALL_ARAF_OBSERVATION_IDS ARRAY COMMENT 'Array of unique observation IDs (from OBSERVATION table) related to ARAF events',
    ALL_ARAF_CONCEPT_CODES ARRAY COMMENT 'Array of all distinct ARAF-related medical concept codes found for the person',
    ALL_ARAF_CONCEPT_DISPLAYS ARRAY COMMENT 'Array of display terms for the ARAF concept codes (from MAPPED_CONCEPTS.CODE_DESCRIPTION)',
    ALL_ARAF_CODE_CATEGORIES_APPLIED ARRAY COMMENT 'Array of code categories applied (will contain \'-ARAF\'-)'
)
COMMENT = 'Dimension table aggregating ARAF-related events for each person, using MAPPED_CONCEPTS and OBSERVATION table. It identifies individuals with any ARAF event meeting criteria defined in VALPROATE_PROG_CODES.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH BaseARAFObservations AS (
    -- Selects ARAF-related observations, applying lookback logic from VALPROATE_PROG_CODES.
    SELECT
        PP."person_id" AS PERSON_ID,
        PAT."sk_patient_id" AS SK_PATIENT_ID,
        O."id" AS OBSERVATION_ID, -- Unique identifier for the observation record
        O."clinical_effective_date"::DATE AS ARAF_EVENT_DATE,
        MC.CONCEPT_CODE AS ARAF_CONCEPT_CODE,
        MC.CODE_DESCRIPTION AS ARAF_CONCEPT_DISPLAY, -- Using CODE_DESCRIPTION from MAPPED_CONCEPTS
        VPC.CODE_CATEGORY AS ARAF_CODE_CATEGORY, -- This will be 'ARAF'
        (VPC.CODE IN ('1366401000000107', '2078951000000106')) AS IS_SPECIFIC_ARAF_FORM_CODE
    FROM
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."OBSERVATION" AS O
    JOIN
        DATA_LAB_NCL_TRAINING_TEMP.CODESETS.MAPPED_CONCEPTS AS MC
        ON O."observation_core_concept_id" = MC.SOURCE_CODE_ID
    JOIN
        DATA_LAB_NCL_TRAINING_TEMP.CODESETS.VALPROATE_PROG_CODES AS VPC
        ON MC.CONCEPT_CODE = VPC.CODE
    JOIN
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT_PERSON" AS PP
        ON O."patient_id" = PP."patient_id"
    JOIN
        "Data_Store_OLIDS_Dummy"."OLIDS_MASKED"."PATIENT" AS PAT
        ON PP."patient_id" = PAT."id"
    WHERE
        VPC.CODE_CATEGORY = 'ARAF'
        AND (
            VPC.LOOKBACK_YEARS_OFFSET IS NULL OR
            O."clinical_effective_date"::DATE >= DATEADD(YEAR, VPC.LOOKBACK_YEARS_OFFSET, CURRENT_DATE())
        )
),
PersonLevelARAFAggregation AS (
    -- Aggregates ARAF information for each person.
    SELECT
        PERSON_ID,
        ANY_VALUE(SK_PATIENT_ID) as SK_PATIENT_ID, -- Assuming PERSON_ID to SK_PATIENT_ID is 1:1
        MIN(ARAF_EVENT_DATE) AS EARLIEST_ARAF_EVENT_DATE,
        MAX(ARAF_EVENT_DATE) AS LATEST_ARAF_EVENT_DATE,
        MAX(CASE WHEN IS_SPECIFIC_ARAF_FORM_CODE THEN ARAF_EVENT_DATE ELSE NULL END) AS LATEST_SPECIFIC_ARAF_FORM_DATE,
        MAX(IS_SPECIFIC_ARAF_FORM_CODE::BOOLEAN) AS HAS_SPECIFIC_ARAF_FORM_MEETING_LOOKBACK,
        ARRAY_AGG(DISTINCT OBSERVATION_ID) WITHIN GROUP (ORDER BY OBSERVATION_ID) AS ALL_ARAF_OBSERVATION_IDS,
        ARRAY_AGG(DISTINCT ARAF_CONCEPT_CODE) WITHIN GROUP (ORDER BY ARAF_CONCEPT_CODE) AS ALL_ARAF_CONCEPT_CODES,
        ARRAY_AGG(DISTINCT ARAF_CONCEPT_DISPLAY) WITHIN GROUP (ORDER BY ARAF_CONCEPT_DISPLAY) AS ALL_ARAF_CONCEPT_DISPLAYS,
        ARRAY_AGG(DISTINCT ARAF_CODE_CATEGORY) WITHIN GROUP (ORDER BY ARAF_CODE_CATEGORY) AS ALL_ARAF_CODE_CATEGORIES_APPLIED
    FROM BaseARAFObservations
    GROUP BY PERSON_ID
)
SELECT
    pla.PERSON_ID,
    pla.SK_PATIENT_ID,
    TRUE AS HAS_ARAF_EVENT,
    pla.EARLIEST_ARAF_EVENT_DATE,
    pla.LATEST_ARAF_EVENT_DATE,
    pla.LATEST_SPECIFIC_ARAF_FORM_DATE,
    COALESCE(pla.HAS_SPECIFIC_ARAF_FORM_MEETING_LOOKBACK, FALSE) AS HAS_SPECIFIC_ARAF_FORM_MEETING_LOOKBACK,
    pla.ALL_ARAF_OBSERVATION_IDS,
    pla.ALL_ARAF_CONCEPT_CODES,
    pla.ALL_ARAF_CONCEPT_DISPLAYS,
    pla.ALL_ARAF_CODE_CATEGORIES_APPLIED
FROM PersonLevelARAFAggregation pla; 