CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_SUMMARY (
    PERSON_ID VARCHAR,
    SK_PATIENT_ID VARCHAR,
    AGE NUMBER,
    -- AF indicators
    IN_AF_61 BOOLEAN, -- On AF-related medications (digoxin, anticoagulants, etc.)
    IN_AF_62 BOOLEAN, -- Missing pulse check
    -- CKD indicators
    IN_CKD_61 BOOLEAN, -- Two consecutive eGFR readings below 60
    IN_CKD_62 BOOLEAN, -- Two consecutive UACR readings above 4
    IN_CKD_63 BOOLEAN, -- Latest UACR reading above 70
    IN_CKD_64 BOOLEAN, -- Specific conditions (AKI, BPH/Gout, Lithium, Microhaematuria)
    -- CVD indicators
    IN_CVD_61 BOOLEAN, -- High QRISK2 (≥20%)
    IN_CVD_62 BOOLEAN, -- Moderate QRISK2 (15-19.99%)
    IN_CVD_63 BOOLEAN, -- Needs statin review
    IN_CVD_64 BOOLEAN, -- Needs high-dose statins
    IN_CVD_65 BOOLEAN, -- Needs moderate-dose statins
    IN_CVD_66 BOOLEAN, -- Needs statin review (75-83 years)
    -- CYP Asthma indicator
    IN_CYP_AST_61 BOOLEAN, -- CYP asthma review needed
    -- Metadata
    LAST_REFRESH_DATE TIMESTAMP,
    INDICATOR_VERSION VARCHAR
)
COMMENT = 'Summary table for LTC LCS case finding indicators. Shows which indicators each person is included in, focusing on indicator flags rather than detailed dimension data.'
TARGET_LAG = '4 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
WITH BasePopulation AS (
    -- Get base population
    SELECT DISTINCT
        bp.PERSON_ID,
        bp.SK_PATIENT_ID,
        age.AGE
    FROM DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.INTERMEDIATE_LTC_LCS_CF_BASE_POPULATION bp
    JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PERSON_AGE age
        USING (PERSON_ID)
)
-- Final selection
SELECT
    bp.PERSON_ID,
    bp.SK_PATIENT_ID,
    bp.AGE,
    -- AF indicators
    COALESCE(af61.HAS_ACTIVE_ANTICOAGULANT OR af61.HAS_ACTIVE_DIGOXIN OR af61.HAS_ACTIVE_CARDIAC_GLYCOSIDE, FALSE) AS IN_AF_61,
    COALESCE(af62.HAS_PULSE_CHECK, FALSE) AS IN_AF_62,
    -- CKD indicators
    COALESCE(ckd61.HAS_CKD, FALSE) AS IN_CKD_61,
    COALESCE(ckd62.HAS_ELEVATED_UACR, FALSE) AS IN_CKD_62,
    COALESCE(ckd63.HAS_ELEVATED_UACR, FALSE) AS IN_CKD_63,
    COALESCE(ckd64.HAS_ACUTE_KIDNEY_INJURY OR ckd64.HAS_BPH_GOUT OR ckd64.HAS_LITHIUM_MEDICATION OR ckd64.HAS_MICROHAEMATURIA, FALSE) AS IN_CKD_64,
    -- CVD indicators
    COALESCE(cvd61.HAS_HIGH_QRISK2, FALSE) AS IN_CVD_61,
    COALESCE(cvd62.HAS_MODERATE_QRISK2, FALSE) AS IN_CVD_62,
    COALESCE(cvd63.NEEDS_STATIN_REVIEW, FALSE) AS IN_CVD_63,
    COALESCE(cvd64.NEEDS_HIGH_DOSE_STATIN, FALSE) AS IN_CVD_64,
    COALESCE(cvd65.NEEDS_MODERATE_DOSE_STATIN, FALSE) AS IN_CVD_65,
    COALESCE(cvd66.NEEDS_STATIN_REVIEW, FALSE) AS IN_CVD_66,
    -- CYP Asthma indicator
    COALESCE(cypast61.HAS_HAD_REVIEW, FALSE) AS IN_CYP_AST_61,
    -- Metadata
    CURRENT_TIMESTAMP() AS LAST_REFRESH_DATE,
    '1.0' AS INDICATOR_VERSION
FROM BasePopulation bp
-- AF indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_AF_61 af61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_AF_62 af62
    USING (PERSON_ID)
-- CKD indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_61 ckd61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_62 ckd62
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_63 ckd63
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CKD_64 ckd64
    USING (PERSON_ID)
-- CVD indicators
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_61 cvd61
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_62 cvd62
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_63 cvd63
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_64 cvd64
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_65 cvd65
    USING (PERSON_ID)
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CVD_66 cvd66
    USING (PERSON_ID)
-- CYP Asthma indicator
LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.HEI_MIGRATION.DIM_PROG_LTC_LCS_CF_CYP_AST_61 cypast61
    USING (PERSON_ID); 