name: Auto-move Assigned Issues to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add In Progress label to assigned issues
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const assignee = context.payload.assignee;
            
            console.log(`Issue #${issue.number} assigned to ${assignee.login}`);
            
            // Get current labels
            const currentLabels = issue.labels.map(label => label.name);
            console.log(`Current labels: ${currentLabels.join(', ')}`);
            
            // Status labels to manage
            const statusLabels = ['In Progress', 'Code Review', 'Done'];
            
            // Remove existing status labels
            const labelsToRemove = currentLabels.filter(label => statusLabels.includes(label));
            for (const label of labelsToRemove) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: label
              });
              console.log(`Removed '${label}' label from issue #${issue.number}`);
            }
            
            // Add "In Progress" label if not already present
            if (!currentLabels.includes('In Progress')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['In Progress']
              });
              console.log(`Added 'In Progress' label to issue #${issue.number}`);
            } else {
              console.log(`Issue #${issue.number} already has 'In Progress' label`);
            }