-- see: https://archive.datadictionary.nhs.uk/DD%20Release%20May%202024/attributes/main_specialty_code.html
{% macro get_main_specialty_description(specialty_column) %}
    case {{ specialty_column }}
        when '100' then 'General Surgery'
        when '101' then 'Urology'
        when '107' then 'Vascular Surgery'
        when '110' then 'Trauma and Orthopaedics'
        when '120' then 'Ear Nose and Throat'
        when '130' then 'Ophthalmology'
        when '140' then 'Oral Surgery'
        when '141' then 'Restorative Dentistry'
        when '142' then 'Paediatric Dentistry'
        when '143' then 'Orthodontics'
        when '145' then 'Oral and Maxillofacial Surgery'
        when '146' then 'Endodontics'
        when '147' then 'Periodontics'
        when '148' then 'Prosthodontics'
        when '149' then 'Surgical Dentistry'
        when '150' then 'Neurosurgery'
        when '160' then 'Plastic Surgery'
        when '170' then 'Cardiothoracic Surgery'
        when '171' then 'Paediatric Surgery'
        when '180' then 'Emergency Medicine'
        when '190' then 'Anaesthetics'
        when '191' then 'Pain Management (Retired 1 April 2004)'
        when '192' then 'Intensive Care Medicine'
        when '200' then 'Aviation and Space Medicine'
        when '300' then 'General Internal Medicine'
        when '301' then 'Gastroenterology'
        when '302' then 'Endocrinology and Diabetes'
        when '303' then 'Clinical Haematology'
        when '304' then 'Clinical Physiology'
        when '305' then 'Clinical Pharmacology'
        when '310' then 'Audio Vestibular Medicine'
        when '311' then 'Clinical Genetics'
        when '312' then 'CLINICAL CYTOGENETICS and MOLECULAR GENETICS (Retired 1 April 2010)'
        when '313' then 'Clinical Immunology'
        when '314' then 'Rehabilitation Medicine'
        when '315' then 'Palliative Medicine'
        when '317' then 'Allergy'
        when '320' then 'Cardiology'
        when '321' then 'Paediatric Cardiology'
        when '325' then 'Sport and Exercise Medicine'
        when '326' then 'Acute Internal Medicine'
        when '330' then 'Dermatology'
        when '340' then 'Respiratory Medicine'
        when '350' then 'Infectious Diseases'
        when '352' then 'Tropical Medicine'
        when '360' then 'Genitourinary Medicine'
        when '361' then 'Renal Medicine'
        when '370' then 'Medical Oncology'
        when '371' then 'Nuclear Medicine'
        when '400' then 'Neurology'
        when '401' then 'Clinical Neurophysiology'
        when '410' then 'Rheumatology'
        when '420' then 'Paediatrics'
        when '421' then 'Paediatric Neurology'
        when '430' then 'Geriatric Medicine'
        when '450' then 'Dental Medicine'
        when '451' then 'Special Care Dentistry'
        when '460' then 'Medical Ophthalmology'
        when '500' then 'Obstetrics and Gynaecology'
        when '501' then 'Obstetrics'
        when '502' then 'Gynaecology'
        when '504' then 'Community Sexual and Reproductive Health'
        when '510' then 'Antenatal Clinic (Retired 1 April 2004)'
        when '520' then 'Postnatal Clinic (Retired 1 April 2004)'
        when '560' then 'Midwifery'
        when '600' then 'General Medical Practice'
        when '601' then 'General Dental Practice'
        when '610' then 'Maternity Function (Retired 1 April 2004)'
        when '620' then 'Other than Maternity (Retired 1 April 2004)'
        when '700' then 'Learning Disability'
        when '710' then 'Adult Mental Illness'
        when '711' then 'Child and Adolescent Psychiatry'
        when '712' then 'Forensic Psychiatry'
        when '713' then 'Medical Psychotherapy'
        when '715' then 'Old Age Psychiatry'
        when '800' then 'Clinical Oncology'
        when '810' then 'Radiology'
        when '820' then 'General Pathology'
        when '821' then 'Blood Transfusion'
        when '822' then 'Chemical Pathology'
        when '823' then 'Haematology'
        when '824' then 'Histopathology'
        when '830' then 'Immunopathology'
        when '831' then 'Medical Microbiology and Virology'
        when '832' then 'Neuropathology (Retired 1 April 2004)'
        when '833' then 'Medical Microbiology'
        when '834' then 'Medical Virology'
        when '900' then 'Community Medicine'
        when '901' then 'Occupational Medicine'
        when '902' then 'Community Health Services Dental'
        when '903' then 'Public Health Medicine'
        when '904' then 'Public Health Dental'
        when '950' then 'Nursing'
        when '960' then 'Allied Health Professional'
        when '990' then 'Joint Consultant Clinics (Retired 1 April 2004)'
        else {{ specialty_column }}
    end
{% endmacro %}